In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("/content/ACLED Data_2026-03-08.csv")

In [3]:
data

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp,population_best
0,BUR3027,2015-01-01,2015,1,Political violence,Battles,Armed clash,Unidentified Armed Group (Burundi),NaN,Political militia,...,-2.8881,29.2047,1,RFI; IWACU; Radio Publique Africaine,National-International,Fighting between unidentified attackers believ...,21,NaN,1572403604,41140.0
1,GAM103,2015-01-01,2015,1,Political violence,Violence against civilians,Abduction/forced disappearance,Military Forces of Gambia (1996-2017) National...,NaN,State forces,...,13.4531,-16.5775,1,HRW,Other,Five people reportedly abducted by men believe...,0,NaN,1618530319,35946.0
2,SUD7377,2015-01-01,2015,1,Political violence,Violence against civilians,Attack,Unidentified Armed Group (Sudan),NaN,Political militia,...,12.4665,23.6998,1,UNAMID,Other,Unidentified actors attack the civilian popula...,0,NaN,1618573802,0.0
3,NIG6859,2015-01-01,2015,1,Political violence,Explosions/Remote violence,Suicide bomb,Unidentified Armed Group (Nigeria),NaN,Political militia,...,10.2897,11.1673,1,Xinhua,International,A suicide bomber blew himself up at the gates ...,1,NaN,1572403790,410565.0
4,YEM32556,2015-01-01,2015,1,Political violence,Explosions/Remote violence,Remote explosive/landmine/IED,Unidentified Armed Group (Yemen),NaN,Political militia,...,13.1287,45.3807,1,Huna Aden; Yemen Saeed; Yemen Data Project,Local partner-National,Member of the popular committees in Abyan repo...,0,NaN,1576530904,51274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831646,NIG47528,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Unidentified Armed Group (Nigeria),NaN,Political militia,...,9.2845,12.3651,1,Local Network,Other,"On 8 March 2025, an unidentified group armed w...",0,NaN,1771884616,NaN
831647,NIG47529,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Katsina Communal Militia (Nigeria),NaN,Identity militia,...,11.7284,7.3509,1,Local Network,Other,"On 8 March 2025, a Katsina militia wounded two...",0,NaN,1771884616,NaN
831648,NIG47530,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Katsina Communal Militia (Nigeria),NaN,Identity militia,...,12.4162,7.4019,2,Local Network,Other,"On 8 March 2025, a Katsina militia killed 2 co...",2,NaN,1771884616,NaN
831649,NIG47531,2025-03-08,2025,1,Political violence,Battles,Armed clash,Islamic State West Africa Province (ISWAP) and...,NaN,Rebel group,...,11.4833,12.3144,1,Local Network,Other,"On 8 March 2025, ISWAP/Boko Haram (JAS) fighte...",2,NaN,1771892277,13456.0
831650,NIG47532,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Fulani Ethnic Militia (Nigeria),Pastoralists (Nigeria),Identity militia,...,7.1971,9.5200,1,Local Network,Other,"On 8 March 2025, for the second consecutive da...",5,NaN,1771884616,NaN

In [4]:
pd.set_option("display.max_columns", None)

In [5]:
# Columns to keep

# "event_id_cnty", "event_date", "disorder_type", "event_type", "actor1",
# "actor2","interaction", " "civilian_targeting", "region", "country", "notes",
# "fatalities"

In [6]:
data

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,assoc_actor_2,inter2,interaction,civilian_targeting,iso,region,country,admin1,admin2,admin3,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp,population_best
0,BUR3027,2015-01-01,2015,1,Political violence,Battles,Armed clash,Unidentified Armed Group (Burundi),NaN,Political militia,Military Forces of Burundi (2005-),CNDD-FDD-Imbonerakure: National Council for th...,State forces,State forces-Political militia,NaN,108,Eastern Africa,Burundi,Cibitoke,Murwi,Murwi,Murwi,-2.8881,29.2047,1,RFI; IWACU; Radio Publique Africaine,National-International,Fighting between unidentified attackers believ...,21,NaN,1572403604,41140.0
1,GAM103,2015-01-01,2015,1,Political violence,Violence against civilians,Abduction/forced disappearance,Military Forces of Gambia (1996-2017) National...,NaN,State forces,Civilians (Gambia),NaN,Civilians,State forces-Civilians,Civilian targeting,270,Western Africa,Gambia,Banjul,Banjul Central,NaN,Banjul,13.4531,-16.5775,1,HRW,Other,Five people reportedly abducted by men believe...,0,NaN,1618530319,35946.0
2,SUD7377,2015-01-01,2015,1,Political violence,Violence against civilians,Attack,Unidentified Armed Group (Sudan),NaN,Political militia,Civilians (Sudan),NaN,Civilians,Political militia-Civilians,Civilian targeting,729,Northern Africa,Sudan,Central Darfur,Wadi Salih,NaN,Sambat,12.4665,23.6998,1,UNAMID,Other,Unidentified actors attack the civilian popula...,0,NaN,1618573802,0.0
3,NIG6859,2015-01-01,2015,1,Political violence,Explosions/Remote violence,Suicide bomb,Unidentified Armed Group (Nigeria),NaN,Political militia,Civilians (Nigeria),Christian Group (Nigeria),Civilians,Political militia-Civilians,Civilian targeting,566,Western Africa,Nigeria,Gombe,Gombe,NaN,Gombe,10.2897,11.1673,1,Xinhua,International,A suicide bomber blew himself up at the gates ...,1,NaN,1572403790,410565.0
4,YEM32556,2015-01-01,2015,1,Political violence,Explosions/Remote violence,Remote explosive/landmine/IED,Unidentified Armed Group (Yemen),NaN,Political militia,Popular Resistance,NaN,Political militia,Political militia-Political militia,NaN,887,Middle East,Yemen,Abyan,Zingibar,NaN,Zinjibar,13.1287,45.3807,1,Huna Aden; Yemen Saeed; Yemen Data Project,Local partner-National,Member of the popular committees in Abyan repo...,0,NaN,1576530904,51274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831646,NIG47528,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Unidentified Armed Group (Nigeria),NaN,Political militia,Civilians (Nigeria),NaN,Civilians,Political militia-Civilians,Civilian targeting,566,Western Africa,Nigeria,Adamawa,Yola-North,NaN,Sangere,9.2845,12.3651,1,Local Network,Other,"On 8 March 2025, an unidentified group armed w...",0,NaN,1771884616,NaN
831647,NIG47529,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Katsina Communal Militia (Nigeria),NaN,Identity militia,Civilians (Nigeria),NaN,Civilians,Identity militia-Civilians,Civilian targeting,566,Western Africa,Nigeria,Katsina,Bakori,NaN,Guga,11.7284,7.3509,1,Local Network,Other,"On 8 March 2025, a Katsina militia wounded two...",0,NaN,1771884616,NaN
831648,NIG47530,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Katsina Communal Militia (Nigeria),NaN,Identity militia,Civilians (Nigeria),NaN,Civilians,Identity militia-Civilians,Civilian targeting,566,Western Africa,Nigeria,Katsina,Safana,NaN,Bode,12.4162,7.4019,2,Local Network,Other,"On 8 March 2025, a Katsina militia killed 2 co...",2,NaN,1771884616,NaN
831649,NIG47531,2025-03-08,2025,1,Political violence,Battles,Armed clash,Islamic State West Africa Province (ISWAP) and...,NaN,Rebel group,Military Forces of Nigeria (2023-),NaN,State forces,State forces-Rebel group,NaN,566,Western Africa,Nigeria,Yobe,Gujba,NaN,Goniri,11.4833,12.3144,1,Local Network,Other,"On 8 March 2025, ISWAP/Boko Haram (JAS) fighte...",2,NaN,1771892277,13456.0
831650,NIG47532,2025-03-08,2025,1,Political violence,Violence against civilians,Attack,Fulani Ethnic Militia (Nigeria),Pastoralists (Nigeria),Identity militia,Civilians (Nigeria),NaN,Civilians,Identity militia-Civilians,Civilian targeting,566,Western Africa,Nigeria,Benue,Katsina Ala,NaN,Mbagena,7.1971,9.5200,1,Local Network,Other,"On 8 March 2025, for the second consecutive da...",5,NaN,1771884616,NaN

In [7]:
data.columns

Index(['event_id_cnty', 'event_date', 'year', 'time_precision',
       'disorder_type', 'event_type', 'sub_event_type', 'actor1',
       'assoc_actor_1', 'inter1', 'actor2', 'assoc_actor_2', 'inter2',
       'interaction', 'civilian_targeting', 'iso', 'region', 'country',
       'admin1', 'admin2', 'admin3', 'location', 'latitude', 'longitude',
       'geo_precision', 'source', 'source_scale', 'notes', 'fatalities',
       'tags', 'timestamp', 'population_best'],
      dtype='object')

In [8]:
data = data[["event_id_cnty", "country", "event_date", "disorder_type", "event_type",
             "interaction", "civilian_targeting", "region", "notes",
"fatalities"]]

In [9]:
data

,event_id_cnty,country,event_date,disorder_type,event_type,interaction,civilian_targeting,region,notes,fatalities
0,BUR3027,Burundi,2015-01-01,Political violence,Battles,State forces-Political militia,NaN,Eastern Africa,Fighting between unidentified attackers believ...,21
1,GAM103,Gambia,2015-01-01,Political violence,Violence against civilians,State forces-Civilians,Civilian targeting,Western Africa,Five people reportedly abducted by men believe...,0
2,SUD7377,Sudan,2015-01-01,Political violence,Violence against civilians,Political militia-Civilians,Civilian targeting,Northern Africa,Unidentified actors attack the civilian popula...,0
3,NIG6859,Nigeria,2015-01-01,Political violence,Explosions/Remote violence,Political militia-Civilians,Civilian targeting,Western Africa,A suicide bomber blew himself up at the gates ...,1
4,YEM32556,Yemen,2015-01-01,Political violence,Explosions/Remote violence,Political militia-Political militia,NaN,Middle East,Member of the popular committees in Abyan repo...,0
...,...,...,...,...,...,...,...,...,...,...
831646,NIG47528,Nigeria,2025-03-08,Political violence,Violence against civilians,Political militia-Civilians,Civilian targeting,Western Africa,"On 8 March 2025, an unidentified group armed w...",0
831647,NIG47529,Nigeria,2025-03-08,Political violence,Violence against civilians,Identity militia-Civilians,Civilian targeting,Western Africa,"On 8 March 2025, a Katsina militia wounded two...",0
831648,NIG47530,Nigeria,2025-03-08,Political violence,Violence against civilians,Identity militia-Civilians,Civilian targeting,Western Africa,"On 8 March 2025, a Katsina militia killed 2 co...",2
831649,NIG47531,Nigeria,2025-03-08,Political violence,Battles,State forces-Rebel group,NaN,Western Africa,"On 8 March 2025, ISWAP/Boko Haram (JAS) fighte...",2
831650,NIG47532,Nigeria,2025-03-08,Political violence,Violence against civilians,Identity militia-Civilians,Civilian targeting,Western Africa,"On 8 March 2025, for the second consecutive da...",5

In [10]:
data = data.sort_values("country").reset_index(drop = True)

In [11]:
data

,event_id_cnty,country,event_date,disorder_type,event_type,interaction,civilian_targeting,region,notes,fatalities
0,ALB349,Albania,2019-03-08,Demonstrations,Riots,State forces-Rioters,NaN,Europe,"On 8 March 2019, residents of Fier demonstrate...",0
1,ALB560,Albania,2019-10-09,Demonstrations,Protests,State forces-Protesters,NaN,Europe,"On 9 October 2019, residents of the Astir area...",0
2,ALB749,Albania,2020-06-24,Demonstrations,Protests,State forces-Protesters,NaN,Europe,"On 24 June 2020, the Alliance for Protection o...",0
3,ALB753,Albania,2020-07-03,Demonstrations,Protests,State forces-Protesters,NaN,Europe,"On 3 July 2020, public transport employees hel...",0
4,ALB471,Albania,2019-06-25,Demonstrations,Riots,State forces-Rioters,NaN,Europe,"On 25 June 2019, about 5000 residents and Demo...",0
...,...,...,...,...,...,...,...,...,...,...
831646,YEM111269,Yemen,2022-12-26,Political violence,Battles,State forces-Political militia,NaN,Middle East,"On 26 December 2022, Houthi forces attempted t...",2
831647,YEM26362,Yemen,2018-12-15,Political violence,Explosions/Remote violence,External/Other forces only,NaN,Middle East,A Saudi-led coalition airstrike hit a civilian...,0
831648,YEM26372,Yemen,2018-12-15,Political violence,Explosions/Remote violence,External/Other forces only,NaN,Middle East,2 Saudi-led coalition airstrikes were launched...,0
831649,YEM26367,Yemen,2018-12-15,Political violence,Explosions/Remote violence,External/Other forces-Civilians,Civilian targeting,Middle East,A child was killed along with a number of catt...,1
831650,YEM49948,Yemen,2020-03-14,Political violence,Explosions/Remote violence,Political militia-Civilians,Civilian targeting,Middle East,"On 14 March 2020, anti-Houthi WCJF fired machi...",0

In [12]:
data["event_date"] = pd.to_datetime(data["event_date"])

In [13]:
data = data.sort_values(by = ["country", "event_date"]).reset_index(drop = True)

In [14]:
data

,event_id_cnty,country,event_date,disorder_type,event_type,interaction,civilian_targeting,region,notes,fatalities
0,ALB9,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,NaN,Europe,"On Feb. 6, 2018: An explosion occurred near th...",0
1,ALB8,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,NaN,Europe,"On Feb. 6, 2018: An explosion occurred in a bu...",0
2,ALB7,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,NaN,Europe,"On Feb. 6, 2018: An explosion with TNT occurre...",0
3,ALB15,Albania,2018-02-12,Demonstrations,Riots,Rioters-External/Other forces,NaN,Europe,"On Feb. 12, 2018: National theater artists for...",0
4,ALB28,Albania,2018-03-21,Demonstrations,Riots,State forces-Rioters,NaN,Europe,"On Mar. 21, 2018: Miners demonstrated in front...",0
...,...,...,...,...,...,...,...,...,...,...
831646,YEM97350,Yemen,2025-03-08,Political violence,Explosions/Remote violence,State forces-State forces,NaN,Middle East,"On 8 March 2025, Houthi forces targeted IRG po...",0
831647,YEM97342,Yemen,2025-03-08,Political violence,Battles,State forces-Political militia,NaN,Middle East,"On 8 March 2025, Giants Brigades forces clashe...",3
831648,YEM97341,Yemen,2025-03-08,Political violence,Battles,State forces-Political militia,NaN,Middle East,"On 8 March 2025, Giant Brigades forces clashed...",3
831649,YEM97333,Yemen,2025-03-08,Political violence,Violence against civilians,State forces-Civilians,Civilian targeting,Middle East,"On 8 March 2025, Houthi forces abducted a mosq...",0
831650,YEM97354,Yemen,2025-03-08,Political violence,Explosions/Remote violence,State forces-State forces,NaN,Middle East,"On 8 March 2025, Houthi forces targeted IRG po...",0

In [15]:
# Dropping actor2 and civilian targeting because of too many Nan values

data = data.drop(["civilian_targeting"], axis = 1)

In [16]:
data

,event_id_cnty,country,event_date,disorder_type,event_type,interaction,region,notes,fatalities
0,ALB9,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,Europe,"On Feb. 6, 2018: An explosion occurred near th...",0
1,ALB8,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,Europe,"On Feb. 6, 2018: An explosion occurred in a bu...",0
2,ALB7,Albania,2018-02-06,Political violence,Explosions/Remote violence,Political militia only,Europe,"On Feb. 6, 2018: An explosion with TNT occurre...",0
3,ALB15,Albania,2018-02-12,Demonstrations,Riots,Rioters-External/Other forces,Europe,"On Feb. 12, 2018: National theater artists for...",0
4,ALB28,Albania,2018-03-21,Demonstrations,Riots,State forces-Rioters,Europe,"On Mar. 21, 2018: Miners demonstrated in front...",0
...,...,...,...,...,...,...,...,...,...
831646,YEM97350,Yemen,2025-03-08,Political violence,Explosions/Remote violence,State forces-State forces,Middle East,"On 8 March 2025, Houthi forces targeted IRG po...",0
831647,YEM97342,Yemen,2025-03-08,Political violence,Battles,State forces-Political militia,Middle East,"On 8 March 2025, Giants Brigades forces clashe...",3
831648,YEM97341,Yemen,2025-03-08,Political violence,Battles,State forces-Political militia,Middle East,"On 8 March 2025, Giant Brigades forces clashed...",3
831649,YEM97333,Yemen,2025-03-08,Political violence,Violence against civilians,State forces-Civilians,Middle East,"On 8 March 2025, Houthi forces abducted a mosq...",0
831650,YEM97354,Yemen,2025-03-08,Political violence,Explosions/Remote violence,State forces-State forces,Middle East,"On 8 March 2025, Houthi forces targeted IRG po...",0

In [17]:
data["country"].nunique()

109

In [18]:
data = data.drop(columns = ["event_id_cnty", "region", "disorder_type"])

In [19]:
data

,country,event_date,event_type,interaction,notes,fatalities
0,Albania,2018-02-06,Explosions/Remote violence,Political militia only,"On Feb. 6, 2018: An explosion occurred near th...",0
1,Albania,2018-02-06,Explosions/Remote violence,Political militia only,"On Feb. 6, 2018: An explosion occurred in a bu...",0
2,Albania,2018-02-06,Explosions/Remote violence,Political militia only,"On Feb. 6, 2018: An explosion with TNT occurre...",0
3,Albania,2018-02-12,Riots,Rioters-External/Other forces,"On Feb. 12, 2018: National theater artists for...",0
4,Albania,2018-03-21,Riots,State forces-Rioters,"On Mar. 21, 2018: Miners demonstrated in front...",0
...,...,...,...,...,...,...
831646,Yemen,2025-03-08,Explosions/Remote violence,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0
831647,Yemen,2025-03-08,Battles,State forces-Political militia,"On 8 March 2025, Giants Brigades forces clashe...",3
831648,Yemen,2025-03-08,Battles,State forces-Political militia,"On 8 March 2025, Giant Brigades forces clashed...",3
831649,Yemen,2025-03-08,Violence against civilians,State forces-Civilians,"On 8 March 2025, Houthi forces abducted a mosq...",0
831650,Yemen,2025-03-08,Explosions/Remote violence,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0

# **Next Steps:**
#create one hot encoding for event_type and interaction
#create embedding using BERT for notes
#do the region week grouping
#create new features

In [20]:
# One hot encoding for event_type and interaction
df = pd.get_dummies(data, columns = ["event_type"], dtype = int)

In [21]:
df

,country,event_date,interaction,notes,fatalities,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians
0,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred near th...",0,0,1,0,0,0,0
1,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred in a bu...",0,0,1,0,0,0,0
2,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion with TNT occurre...",0,0,1,0,0,0,0
3,Albania,2018-02-12,Rioters-External/Other forces,"On Feb. 12, 2018: National theater artists for...",0,0,0,0,1,0,0
4,Albania,2018-03-21,State forces-Rioters,"On Mar. 21, 2018: Miners demonstrated in front...",0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
831646,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0
831647,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giants Brigades forces clashe...",3,1,0,0,0,0,0
831648,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giant Brigades forces clashed...",3,1,0,0,0,0,0
831649,Yemen,2025-03-08,State forces-Civilians,"On 8 March 2025, Houthi forces abducted a mosq...",0,0,0,0,0,0,1
831650,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0

In [22]:
df[["actor1", "actor2"]] = df["interaction"].str.split("-", expand=True)

In [23]:
df

,country,event_date,interaction,notes,fatalities,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,actor1,actor2
0,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred near th...",0,0,1,0,0,0,0,Political militia only,None
1,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred in a bu...",0,0,1,0,0,0,0,Political militia only,None
2,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion with TNT occurre...",0,0,1,0,0,0,0,Political militia only,None
3,Albania,2018-02-12,Rioters-External/Other forces,"On Feb. 12, 2018: National theater artists for...",0,0,0,0,1,0,0,Rioters,External/Other forces
4,Albania,2018-03-21,State forces-Rioters,"On Mar. 21, 2018: Miners demonstrated in front...",0,0,0,0,1,0,0,State forces,Rioters
...,...,...,...,...,...,...,...,...,...,...,...,...,...
831646,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,State forces,State forces
831647,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giants Brigades forces clashe...",3,1,0,0,0,0,0,State forces,Political militia
831648,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giant Brigades forces clashed...",3,1,0,0,0,0,0,State forces,Political militia
831649,Yemen,2025-03-08,State forces-Civilians,"On 8 March 2025, Houthi forces abducted a mosq...",0,0,0,0,0,0,1,State forces,Civilians
831650,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,State forces,State forces

In [24]:
df["actor1"] = df["actor1"].str.replace(" only", "", regex=False)
df["actor2"] = df["actor2"].str.replace(" only", "", regex=False)

In [25]:
actors = pd.concat([df["actor1"], df["actor2"]])

In [26]:
actors.value_counts()

State forces             429201
External/Other forces    312951
Political militia        226712
Rebel group              210847
Civilians                188924
Identity militia          43215
Protesters                22680
Rioters                   19435
Name: count, dtype: int64

In [27]:
actor1_dummies = pd.get_dummies(df["actor1"], prefix="actor", dtype=int)
actor2_dummies = pd.get_dummies(df["actor2"], prefix="actor", dtype=int)

In [28]:
actor_features = actor1_dummies.add(actor2_dummies, fill_value=0)

In [29]:
actor_features

,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces
0,0.0,0,0,1,0,0,0,0
1,0.0,0,0,1,0,0,0,0
2,0.0,0,0,1,0,0,0,0
3,0.0,1,0,0,0,0,1,0
4,0.0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...
831646,0.0,0,0,0,0,0,0,2
831647,0.0,0,0,1,0,0,0,1
831648,0.0,0,0,1,0,0,0,1
831649,1.0,0,0,0,0,0,0,1
831650,0.0,0,0,0,0,0,0,2

In [30]:
df = pd.concat([df, actor_features], axis=1)

In [31]:
df

,country,event_date,interaction,notes,fatalities,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,actor1,actor2,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces
0,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred near th...",0,0,1,0,0,0,0,Political militia,None,0.0,0,0,1,0,0,0,0
1,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion occurred in a bu...",0,0,1,0,0,0,0,Political militia,None,0.0,0,0,1,0,0,0,0
2,Albania,2018-02-06,Political militia only,"On Feb. 6, 2018: An explosion with TNT occurre...",0,0,1,0,0,0,0,Political militia,None,0.0,0,0,1,0,0,0,0
3,Albania,2018-02-12,Rioters-External/Other forces,"On Feb. 12, 2018: National theater artists for...",0,0,0,0,1,0,0,Rioters,External/Other forces,0.0,1,0,0,0,0,1,0
4,Albania,2018-03-21,State forces-Rioters,"On Mar. 21, 2018: Miners demonstrated in front...",0,0,0,0,1,0,0,State forces,Rioters,0.0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831646,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,State forces,State forces,0.0,0,0,0,0,0,0,2
831647,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giants Brigades forces clashe...",3,1,0,0,0,0,0,State forces,Political militia,0.0,0,0,1,0,0,0,1
831648,Yemen,2025-03-08,State forces-Political militia,"On 8 March 2025, Giant Brigades forces clashed...",3,1,0,0,0,0,0,State forces,Political militia,0.0,0,0,1,0,0,0,1
831649,Yemen,2025-03-08,State forces-Civilians,"On 8 March 2025, Houthi forces abducted a mosq...",0,0,0,0,0,0,1,State forces,Civilians,1.0,0,0,0,0,0,0,1
831650,Yemen,2025-03-08,State forces-State forces,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,State forces,State forces,0.0,0,0,0,0,0,0,2

In [32]:
df = df.drop(["interaction", "actor1", "actor2"], axis = 1)

In [33]:
df

,country,event_date,notes,fatalities,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces
0,Albania,2018-02-06,"On Feb. 6, 2018: An explosion occurred near th...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0
1,Albania,2018-02-06,"On Feb. 6, 2018: An explosion occurred in a bu...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0
2,Albania,2018-02-06,"On Feb. 6, 2018: An explosion with TNT occurre...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0
3,Albania,2018-02-12,"On Feb. 12, 2018: National theater artists for...",0,0,0,0,1,0,0,0.0,1,0,0,0,0,1,0
4,Albania,2018-03-21,"On Mar. 21, 2018: Miners demonstrated in front...",0,0,0,0,1,0,0,0.0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831646,Yemen,2025-03-08,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,0.0,0,0,0,0,0,0,2
831647,Yemen,2025-03-08,"On 8 March 2025, Giants Brigades forces clashe...",3,1,0,0,0,0,0,0.0,0,0,1,0,0,0,1
831648,Yemen,2025-03-08,"On 8 March 2025, Giant Brigades forces clashed...",3,1,0,0,0,0,0,0.0,0,0,1,0,0,0,1
831649,Yemen,2025-03-08,"On 8 March 2025, Houthi forces abducted a mosq...",0,0,0,0,0,0,1,1.0,0,0,0,0,0,0,1
831650,Yemen,2025-03-08,"On 8 March 2025, Houthi forces targeted IRG po...",0,0,1,0,0,0,0,0.0,0,0,0,0,0,0,2

In [34]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [35]:
from sentence_transformers import SentenceTransformer
import torch

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(
    df["notes"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [36]:
import numpy as np

embeddings_df = pd.DataFrame(
    embeddings,
    columns=[f"bert_{i}" for i in range(embeddings.shape[1])]
)

In [37]:
embeddings_df

,bert_0,bert_1,bert_2,bert_3,bert_4,bert_5,bert_6,bert_7,bert_8,bert_9,bert_10,bert_11,bert_12,bert_13,bert_14,bert_15,bert_16,bert_17,bert_18,bert_19,bert_20,bert_21,bert_22,bert_23,bert_24,bert_25,bert_26,bert_27,bert_28,bert_29,bert_30,bert_31,bert_32,bert_33,bert_34,bert_35,bert_36,bert_37,bert_38,bert_39,bert_40,bert_41,bert_42,bert_43,bert_44,bert_45,bert_46,bert_47,bert_48,bert_49,bert_50,bert_51,bert_52,bert_53,bert_54,bert_55,bert_56,bert_57,bert_58,bert_59,bert_60,bert_61,bert_62,bert_63,bert_64,bert_65,bert_66,bert_67,bert_68,bert_69,bert_70,bert_71,bert_72,bert_73,bert_74,bert_75,bert_76,bert_77,bert_78,bert_79,bert_80,bert_81,bert_82,bert_83,bert_84,bert_85,bert_86,bert_87,bert_88,bert_89,bert_90,bert_91,bert_92,bert_93,bert_94,bert_95,bert_96,bert_97,bert_98,bert_99,bert_100,bert_101,bert_102,bert_103,bert_104,bert_105,bert_106,bert_107,bert_108,bert_109,bert_110,bert_111,bert_112,bert_113,bert_114,bert_115,bert_116,bert_117,bert_118,bert_119,bert_120,bert_121,bert_122,bert_123,bert_124,bert_125,bert_126,bert_127,bert_128,bert_129,bert_130,bert_131,bert_132,bert_133,bert_134,bert_135,bert_136,bert_137,bert_138,bert_139,bert_140,bert_141,bert_142,bert_143,bert_144,bert_145,bert_146,bert_147,bert_148,bert_149,bert_150,bert_151,bert_152,bert_153,bert_154,bert_155,bert_156,bert_157,bert_158,bert_159,bert_160,bert_161,bert_162,bert_163,bert_164,bert_165,bert_166,bert_167,bert_168,bert_169,bert_170,bert_171,bert_172,bert_173,bert_174,bert_175,bert_176,bert_177,bert_178,bert_179,bert_180,bert_181,bert_182,bert_183,bert_184,bert_185,bert_186,bert_187,bert_188,bert_189,bert_190,bert_191,bert_192,bert_193,bert_194,bert_195,bert_196,bert_197,bert_198,bert_199,bert_200,bert_201,bert_202,bert_203,bert_204,bert_205,bert_206,bert_207,bert_208,bert_209,bert_210,bert_211,bert_212,bert_213,bert_214,bert_215,bert_216,bert_217,bert_218,bert_219,bert_220,bert_221,bert_222,bert_223,bert_224,bert_225,bert_226,bert_227,bert_228,bert_229,bert_230,bert_231,bert_232,bert_233,bert_234,bert_235,bert_236,bert_237,bert_238,bert_239,bert_240,bert_241,bert_242,bert_243,bert_244,bert_245,bert_246,bert_247,bert_248,bert_249,bert_250,bert_251,bert_252,bert_253,bert_254,bert_255,bert_256,bert_257,bert_258,bert_259,bert_260,bert_261,bert_262,bert_263,bert_264,bert_265,bert_266,bert_267,bert_268,bert_269,bert_270,bert_271,bert_272,bert_273,bert_274,bert_275,bert_276,bert_277,bert_278,bert_279,bert_280,bert_281,bert_282,bert_283,bert_284,bert_285,bert_286,bert_287,bert_288,bert_289,bert_290,bert_291,bert_292,bert_293,bert_294,bert_295,bert_296,bert_297,bert_298,bert_299,bert_300,bert_301,bert_302,bert_303,bert_304,bert_305,bert_306,bert_307,bert_308,bert_309,bert_310,bert_311,bert_312,bert_313,bert_314,bert_315,bert_316,bert_317,bert_318,bert_319,bert_320,bert_321,bert_322,bert_323,bert_324,bert_325,bert_326,bert_327,bert_328,bert_329,bert_330,bert_331,bert_332,bert_333,bert_334,bert_335,bert_336,bert_337,bert_338,bert_339,bert_340,bert_341,bert_342,bert_343,bert_344,bert_345,bert_346,bert_347,bert_348,bert_349,bert_350,bert_351,bert_352,bert_353,bert_354,bert_355,bert_356,bert_357,bert_358,bert_359,bert_360,bert_361,bert_362,bert_363,bert_364,bert_365,bert_366,bert_367,bert_368,bert_369,bert_370,bert_371,bert_372,bert_373,bert_374,bert_375,bert_376,bert_377,bert_378,bert_379,bert_380,bert_381,bert_382,bert_383
0,-0.003974,0.057839,-0.023864,0.013640,0.065623,-0.007908,-0.020057,0.019480,-0.048654,0.073403,0.068225,0.041850,0.035987,-0.016405,-0.000074,0.032849,-0.056953,-0.031694,-0.014113,-0.032365,-0.043954,0.065842,0.013307,-0.011615,4.197361e-02,0.031417,-0.001855,0.008511,0.012495,-0.031299,0.080728,-0.064527,-0.054790,-0.012554,0.105447,-0.015077,0.086048,0.020692,-0.004153,-0.001239,0.023915,-0.039077,0.011872,-0.004467,-0.069668,0.058318,-0.008851,-0.035183,0.042661,0.009080,-0.032043,0.024269,0.070337,-0.021088,0.003516,-0.127151,0.008281,-0.041446,0.018900,-0.009805,0.036528,0.039516,-0.011434,0.047036,0.082390,0.005486,0.024388,-0.019451,0.079658,0.014301,0.144788,-0.097717,0.050641,-0.118364,-0.044985,-0.047868,0.062575,-0.019625,-0.025143,0.001438,0.016911,-0.022094,-0.007903,-0.078122,0.030539,0.036594,-0.014598,0.049298,0.007395,0.046449,-0.053466,0.082889,0.078278,0.029377,0.128948,0.007307,-0.057149,0.023335,-0.045215,0.050690,0.024214,0.004338,-0.088420,-0.052494,-0.009898,0.002484,-0.011436,-0.050061,-0.065480,0.039495,0.016693,-0.051413,-0.004576,-0.086723,0.068047,0.011137,0.032452,0.044178,-0.115011,-0.011678,0.067976,-0.047684,-0.136307,0.077899,0.014479,0.077646,0.026334,-3.147346e-33,-0.026234,0.023108,-0.092774,0.026405,0.057635,-0.025354,-0.030205,0.015172,-0.008013,0.046502,-0.043412,-0.005759,-0.009346,-0.074648,-0.055954,-0.003518,0.094678,0.078539,-0.069042,-0.065113,-0.026858,0.077307,-0.041350,0.033855,-0.000448,0.107191,-0.004129,-0.015138,0.011550,-0.001668,-0.038118,0.094220,-0.031291,0.027039,0.025419,0.052956,-0.058790,-0.026118,-0.083981,-0.022227,-0.020715,0.044886,-0.028267,0.030331,-0.029364,0.005991,-0.050153,0.015295,0.093344,-0.124239,-0.062278,-0.023560,-0.046560,0.024296,-0.006347,0.035368,-0.019453,0.004203,0.121147,0.011106,0.053612,-0.028580,-0.051108,0.013440,0.023430,-0.163248,-0.008870,0.054727,0.077440,0.024042,-0.021310,0.071893,0.009177,-0.040104,-0.053439,-0.028155,-0.021401,0.001995,-0.039991,0.055632,0.056973,-0.011575,0.085981,0.009120,0.010197,0.007445,-0.028316,0.070571,-0.035675,0.055582,-0.022661,-0.059300,-0.002875,-0.024110,-0.094192,-6.260389e-35,-0.037051,-0.002435,-0.136722,-0.015011,-0.019059,0.054836,-0.096248,0.044026,-0.088108,-0.032832,0.028291,-0.029629,0.042096,0.027275,0.024384,-0.013323,0.073610,-0.017722,-0.036165,-0.015262,-0.058792,-0.050946,-0.062182,-0.015656,-0.023338,0.091023,0.009487,-0.003848,0.007564,0.032213,-0.068243,0.010477,-0.050486,0.064018,0.082674,0.131737,0.073984,0.014681,-0.012758,0.013677,-0.014848,0.119180,0.017881,0.077697,0.003850,-0.092583,0.009746,-0.012834,-0.092966,-0.006414,0.010616,0.012598,-0.060262,0.017759,0.028329,0.065112,-0.028188,-0.071840,-0.004413,-0.036444,-0.051421,0.039466,-0.104710,0.030383,-0.043166,-0.018697,-0.137920,-0.033723,-0.033543,0.032973,0.032377,0.045057,-0.041100,-0.069903,-0.097933,-0.018726,0.045977,0.017316,-0.044137,-0.039565,0.014395,-0.073067,-0.039135,0.035383,-0.009397,0.010610,0.121847,0.010316,0.050394,-0.054765,-0.058889,-0.010347,-0.042658,0.029264,0.000844,-3.420973e-08,-0.037028,0.043041,-0.058578,-0.023944,0.087618,0.022338,0.031391,0.020836,-0.059350,0.046708,0.001744,0.010415,0.004516,-0.087336,-0.034107,0.048590,-0.019609,-0.025593,-0.013644,-0.021393,-0.010601,0.019669,-0.036120,0.001708,-0.024377,0.115154,-0.042417,-0.007052,-0.001122,0.041312,-0.041821,0.016221,-0.070225,-0.072633,-0.036750,0.060024,0.085376,-0.015823,0.043469,-0.105231,-0.058401,-0.023530,0.019566,0.063028,0.024369,0.005474,-0.018613,-0.124406,-0.001913,-0.021623,-0.017519,0.011569,-0.021456,0.082288,0.067318,-0.079349,0.000961,0.002978,-0.014745,-0.019325,0.034108,0.009476,0.001720,0.029705
1,0.022458,0.044925,0.039747,0.023597,0.021986,-0.057277,-0.000741,-0.016564,-0.013065,0.011654,0.075367,0.002932,0.014697,-0.024187,0.024339,0.045920,-0.035259,-0.086158,-0.046300,0.050278,0.025874,0.036318,-0.026445,0.058535,5.168880e-02,0.039180,0.051785,0.032888,0.016418,-0.016323,0.084501,-0.092532,-0.043348,0.021583,0.060729,0.023576,0.109246,0.018657,0.094654,0.019304,-0.013653,-0.046792,-0.013402,-0.058694,-0.035903,0.034241,0.029853,-0.060629,-0.005544,-0.007265,-0.001255,-0.007355,0.021900,-0.012923,0.047029,-0.152121,-0.065566,0.018007,0.026365,-0.008013,-0.019172,0.052784,-0.015974,-0.001819,0.018357,-0.042830,0.112364,-0.047795,0.064060,-0.003060,0.139628,-0.030296,0.089475,-0.155869,-0.066405,0.017289,-0.015769,-0.025513,-0.015169,0.001433,0.045130,-0.095726,0.001264,-0.035273,-0.007682,0.023317,-0.004433,0.103853,0.044245,0.021951,-0.039467,0.050709,0.001923,0.060226,0.062383,-0.003186,-0.074648,-0.047402,0.023564,0.060255,-0.081479,0.049157,0.024860,-0.030029,-0.048061,-0.032066,-0.088558,0.047331,-0.061371,-0.048401,0.007404,0.031496,0.037005,-0.085704,-0.004917,0.034947,0.051381,0.006035,-0.133035,0.026749,0.064886,-0.011124,-0.071255,0.056510,-0.045299,0.005778,0.012940,-1.818647e-33,0.019954,-0.029723,-0.018770,0.004586,0.065673,-0.018295,-0.089583,0.008691,-0.042817,0.003169,0.035436,-0.084591,0.002424,-0.005575,-0.015497,0.017372,0.082877,0.026761,-0.032651,-0.081321,-0.010087,0.009584,-0.046876,-0.000664,-0.005014,0.135297,0.084623,0.017568,-0.038358,0.012136,-0.001470,0.040910,-0.056165,0.022575,-0.052196,0.069872,-0.098263,-0.070733,-0.026580,-0.083625,-0.010334,-0.051873,-0.046064,0.028465,0.014491,0.071387,-0.040485,-0.019957,0.091019,-0.049079,-0.026829,-0.019726,-0.060967,0.113083,-0.012900,0.030261,-0.040700,-0.021349,0.103858,0.043410,0.082953,0.019610,-0.073645,0.023123,-0.039053,-0.156150,-0.048844,0.031608,0.029008,0.088554,0.026858,-0.014313,0.031634,0.040669,-0.090605,-0.075047,-0.026289,-0.005686,0.032952,0.115328,0.043085,-0.005072,0.077184,-0.000016,-0.040254,0.053180,0.000275,0.004817,-0.098255,0.041693,-0.103458,-0.065166,-0.038684,-0.025195,-0.064073,-1.527736e-33,-0.001738,0.016862,-0.063760,0.017518,-0.025406,0.052023,-0.039932,0.067940,-0.104137,-0.022006,-0.017741,0.027999,-0.008051,0.048040,0.057073,-0.035344,0.078645,-0.037330,-0.012303,0.015337,-0.029900,-0.015614,-0.030991,-0.033484,0.046835,0.029873,0.013200,-0.020094,0.011075,0.025603,-0.066332,0.048138,-0.024940,0.068465,0.042651,0.063250,0.080498,0.010561,0.005590,-0.052848,-0.022848,0.109099,-0.009273,0.150805,0.001811,0.002574,0.006978,-0.039276,-0.010854,-0.014891,-0.003633,0.066532,-0.056640,-0.047150,0.059404,0.002853,-0.078229,-0.100095,-0.075013,-0.037188,-0.039663,0.030284,-0.081052,0.045197,-0.026825,-0.000082,-0.055193,-0.059299,0.015467,0.018737,0.023148,0.032661,-0.092749,-0.036420,-0.050406,-0.004661,-0.039336,0.063419,-0.047424,0.001697,0.124880,0.003846,-0.056862,0.043533,0.035280,0.000334,0.069150,0.017337,0.040805,-0.052717,-0.055407,0.041737,-0.014309,0.044009,0.023734,-3.336655e-08,-0.055294,0.029655,-0.019357,-0.054427,0.038458,-0.028767,0.054250,0.050082,-0.068724,0.033226,-0.040695,-0.012022,-0.024501,0.056286,-0.107818,0.017007,-0.025989,-0.049592,-0.014533,-0.027511,0.006717,0.012913,0.023257,0.020099,-0.001000,0.045621,-0.037539,0.018266,-0.063276,0.056635,0.018603,-0.003802,-0.058170,-0.033025,-0.073722,0.061082,0.021350,0.011561,-0.033427,-0.068441,-0.025510,-0.075268,0.108100,0.022114,0.019656,0.019791,-0.082260,-0.047007,0.002124,0.037105,0.053133,0.002453,0.002446,0.070103,-0.025172,-0.050843,-0.008566,-0.047572,0.050793,-0.062165,0.077797,-0.033391,-0.032597,0.031741
2,-0.032216,0.053874,-0.056166,-0.003603,0.021312,-0.098377,0.110736,0.044709,0.021153,-0.062096,0.082193,0.058947,0.051996,0.063790,0.018632,-0.060688,-0.021372,-0.067203,-0.074206,-0.045537,-0.010669,0.055088,0.044602,0.071709,1.806997e-02,0.023234,0.041136,0.004978,-0.000958,0.010099,0.041605,-0.056510,-0.132762,-0.011153,0.093561,0.032871,0.012586,0.009395,0.086657,-0.010871,0.035074,-0.064874,-0.041797,-0.011858,0.005694,0.016617,0.036958,-0.048389,0.062907,0.024024,-0.030343,-0.016572,0.062761,-0.055159,-0.014654,-0.090104,0.048735,-0.000980,-0.004069,-0.017716,-0.022554,0.041413,-0.013115,-0.013081,0.030215,0.026021,0.123625,-0.005400,0.085032,-0.079598,0.139927,-0.042274,0.052853,0.024887,-0.050489,-0.054840,0.053223,0.003574,-0.065070,0.017636,0.069406,-0.053528,-0.013952,-0.039200,0.016737,0.042620,-0.036925,0.044433,0.051712,0.069531,0.013950,0.070363,0.072553,-0.050869,0.083021,-0.009312,-0.017178,-0.042392,-0.037847,0.066302,0.001091,0.021275,-0.091934,0.002780,0.001554,-0.022783,-0.075521,-0.010696,-0.036528,0.014198,0.019495,-0.005658,0.036165,-0.072517,0.011950,0.051181,0.009948,0.062475,-0.057900,-0.044082,-0.019273,0.055586,-0.110871,0.050624,-0.047085,0.049521,-0.010151,-1.069184e-33,-0.028955,0.090904,-0.018229,0.018074,0.029905,0.030538,-0.074290,-0.020605,-0.006093,-0.052580,-0.079293,-0.137680,-0.015564,-0.043158,-0.015218,-0.015010,0.037509,0.064440,-0.003304,-0.081841,-0.053136,0.010307,-0.015127,0.003830,-0.043875,0.125517,-0.000901,0.014148,0.011664,0.010236,-0.036757,0.044524,-0.033392,-0.051419,0.020623,0.013469,-0.112441,-0.000648,-0.027332,-0.019311,-0.042695,0.039649,-0.031800,0.074959,-0.005966,0.011001,-0.071797,0.081037,0.039985,-0.166182,-0.061758,-0.019329,0.029665,-0.022348,-0.006124,0.051656,0.017053,-0.027936,0.121063,0.046630,0.137653,0.025958,-0.067320,0.098932,0.007247,-0.047298,-0.049705,-0.003181,0.062446,0.030584,-0.028966,0.013010,0.031667,-0.028507,-0.067317,0.033447,-0.023184,-0.015531,-0.029666,0.031381,-0.036212,-0.046586,0.175049,0.031524,-0.054545,0.054114,-0.009669,-0.017347,0.003902,0.072044,-0.067433,-0.065439,0.039303,-0.018250,-0.028274,-1.253012e-33,0.033332,0.073026,-0.067266,-0.043739,-0.024321,-0.014943,-0.061833,0.015732,-0.047855,0.027272,0.031972,-0.025044,0.008855,0.030738,0.025241,0.079946,0.082186,0.029552,-0.019057,-0.013859,-0.088886,-0.051259,-0.043192,0.017137,-0.006712,0.011062,0.063755,-0.019905,0.003332,-0.030116,-0.014549,-0.002889,-0.023317,0.079435,0.013898,0.094082,0.082749,-0.015988,0.053193,-0.010209,0.012013,0.110486,-0.014054,0.125409,-0.067660,-0.028807,0.046105,-0.020963,-0.022979,-0.127542,-0.010920,-0.000647,-0.010175,-0.020692,0.030983,-0.020611,0.001122,-0.028628,-0.005711,-0.091748,-0.003815,0.012212,-0.049136,0.026136,-0.050040,-0.043103,-0.059245,-0.030081,0.020096,-0.054962,0.086835,-0.033494,-0.037950,-0.033078,-0.084185,0.018338,-0.035759,0.048511,-0.022433,-0.035555,0.081937,-0.047099,-0.108165,0.010090,0.018965,-0.002057,0.072207,0.018704,0.052470,-0.048312,-0.063123,-0.006523,-0.001362,0.043195,0.098210,-3.641112e-08,0.045453,0.018052,-0.040895,0.014874,0.001484,-0.012992,0.066313,0.041436,-0.042243,0.022308,-0.125578,-0.039349,-0.011880,-0.015208,-0.077135,0.080007,-0.058281,0.053638,-0.020364,-0.045471,0.051410,0.003951,0.027462,-0.034412,-0.002276,0.014246,-0.006698,0.013507,-0.014744,-0.020452,-0.021094,-0.058886,-0.066065,-0.074635,-0.056912,0.064781,0.033201,-0.016392,0.028645,-0.068931,-0.125199,-0.030885,-0.023251,0.045043,-0.004473,-0.027724,-0.014020,-0.018801,-0.028018,0.034327,0.039256,0.024588,0.047017,0.052051,0.015565,-0.013258,-0.032057,-0.046443,0.006573,-0.009546,0.098966,-0.044275,0.051180,-0.039614
3,0.041451,0.060823,0.027797,0.038895,0.028736,0.116989,0.043393,-0.144543,0.005008,-0.022823,-0.025945,0.020813,0.047004,0.038058,0.007332,-0.007054,0.095035,-0.025240,0.001392,0.038195,-0.056347,-0.061297,-0.054216,0.029580,-2.965478e-02,-0.068390,0.009031,0.013045,0.017465,-0.002805,-0.063461,-0.005919,-0.070654,0.063439,0.060583,0.050999,0.018804,-0.025747,-0.002985,0.000871,0.020348,-0.011700,-0.037369,0.020175,0.021169,-0.000382,-0.080777,-0.005063,-0.020549,0.005990,-0.019516,0.018712,0.037562,-0.072300,-0.000741,-0.078480,0.061870,0.034056,0.066155,0.049109,-0.016393,-0.025216,-0.020070,0.030134,0.036283,0.040564,-0.002451,0.017556,0.093472,-0.009130,0.024671,-0.023546,0.047087,-0.090161,-0.001429,0.004939,-0.076150,-0.034233,0.020590,-0.121122,0.114617,-0.070202,-0.024921,-0.011817,0.016917,0.023862,-0.043784,0.029216,0.037443,0.034070,-0.002062,0.010413,0.011631,0.058735,0.133393,-0.077042,-0.019520,-0.024967,0.014274,0.054980,0.052875,0.042876,0.032358,-0.064551,-0.044932,-0.046790,0.007036,-0.020154,-0.150381,0.041239,0.021658,0.062482,0.045678,0.018744,0.054506,0.085606,-0.020181,-0.023039,0.019189,-0.036327,-0.016894,0.026284,-0.024959,0.029487,-0.080383,-0.010991,-0.049207,-3.074741e-33,-0.009452,-0.030238,-0.010895,-0.032407,0.014785,-0.053062,-0.048056,0.003950,0.060819,-0.038846,0.074095,-0.073922,0.051134,-0.023727,-0.023354,0.035194,0.005876,0.049993,-0.030997,0.015893,0.002115,0.011289,-0.036656,0.083750,-0.108687,0.105934,-0.082867,0.017116,0.025141,0.001015,-0.041089,0.014943,0.083194,0.043857,0.089624,-0.047682,0.029595,-0.026732,-0.020712,-0.047231,-0.029018,0.037618,-0.046695,0.040779,-0.029102,0.054160,-0.022435,-0.042603,0.022358,0.046287,-0.036498,0.147584,-0.042664,-0.024653,0.023112,-0.013923,-0.039030,-0.049137,0.029454,-0.144653,0.066934,0.122300,0.027675,0.045701,0.019015,-0.053799,-0.010790,0.007960,0.063857,-0.045075,-0.067716,0.021940,0.020809,0.000665,-0.022583,-0.025053,0.027059,-0.021558,0.058503,-0.023356,0.021164,0.030915,0.019868,-0.008584,-0.008799,-0.020034,-0.018256,-0.019120,0.009290,0.058927,0.043893,-0.017186,-0.054530,0.052617,-0.015388,4.367132e-34,0.099784,0.013698,-0.030195,-0.027949,-0.016646,-0.101055,-0.073350,0.068985,0.112653,0.040611,0.005349,-0.013974,0.045824,0.027575,-0.019315,-0.135718,0.028132,0.077897,-0.003753,0.023674,-0.006607,-0.027474,-0.013781,-0.083889,-0.032519,0.094881,0.085951,0.025317,-0.088239,-0.009209,0.059284,-0.025226,-0.005227,0.016171,0.025344,-0.017794,0.133870,-0.023943,-0.105041,-0.031904,-0.040052,0.073717,-0.057207,0.135782,-0.053970,0.001268,-0.017856,0.000620,-0.035258,-0.045023,-0.045228,-0.010970,0.060224,-0.160315,-0.002745,-0.027717,-0.009936,-0.023926,0.028300,0.080878,-0.011485,0.014723,-0.108740,-0.141163,0.010661,0.047984,-0.074077,0.095326,0.016158,0.054364,0.062044,-0.005749,0.005071,0.049897,-0.065684,-0.026327,0.062161,0.005239,-0.015408,-0.019706,0.016647,-0.047994,-0.048874,0.009182,0.021023,0.146561,-0.001915,-0.045705,-0.064043,0.011443,0.024232,-0.058137,0.055365,-0.010568,-0.017417,-3.614149e-08,-0.074953,0.012596,0.004302,-0.035575,0.055553,-0.017649,-0.016342,-0.028112,0.030373,0.038392,-0.004935,-0.065183,0.053733,-0.037269,-0.040340,-0.029306,0.009488,-0.060725,-0.087625,-0.042691,-0.052400,-0.019189,0.038741,-0.019295,-0.030219,0.031830,-0.051026,-0.027279,-0.069179,0.111247,-0.092308,0.017067,-0.039225,-0.013072,-0.029676,0.040501,-0.009389,-0.061023,0.036908,-0.125279,-0.007119,0.010780,0.052914,0.024843,0.004467,0.003946,0.061856,0.039128,-0.024055,0.012994,-0.076158,-0.060181,-0.050613,0.043946,0.030683,-0.042630,0.020646,0.084593,-0.006898,0.062060,-0.020137,-0.013739,-0.018947,0.014590

In [38]:
#embeddings_df = pd.read_csv("/content/embeddings_df.csv")

In [39]:
df = pd.concat([df.reset_index(drop=True), embeddings_df], axis=1)

In [40]:
df

,country,event_date,notes,fatalities,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces,bert_0,bert_1,bert_2,bert_3,bert_4,bert_5,bert_6,bert_7,bert_8,bert_9,bert_10,bert_11,bert_12,bert_13,bert_14,bert_15,bert_16,bert_17,bert_18,bert_19,bert_20,bert_21,bert_22,bert_23,bert_24,bert_25,bert_26,bert_27,bert_28,bert_29,bert_30,bert_31,bert_32,bert_33,bert_34,bert_35,bert_36,bert_37,bert_38,bert_39,bert_40,bert_41,bert_42,bert_43,bert_44,bert_45,bert_46,bert_47,bert_48,bert_49,bert_50,bert_51,bert_52,bert_53,bert_54,bert_55,bert_56,bert_57,bert_58,bert_59,bert_60,bert_61,bert_62,bert_63,bert_64,bert_65,bert_66,bert_67,bert_68,bert_69,bert_70,bert_71,bert_72,bert_73,bert_74,bert_75,bert_76,bert_77,bert_78,bert_79,bert_80,bert_81,bert_82,bert_83,bert_84,bert_85,bert_86,bert_87,bert_88,bert_89,bert_90,bert_91,bert_92,bert_93,bert_94,bert_95,bert_96,bert_97,bert_98,bert_99,bert_100,bert_101,bert_102,bert_103,bert_104,bert_105,bert_106,bert_107,bert_108,bert_109,bert_110,bert_111,bert_112,bert_113,bert_114,bert_115,bert_116,bert_117,bert_118,bert_119,bert_120,bert_121,bert_122,bert_123,bert_124,bert_125,bert_126,bert_127,bert_128,bert_129,bert_130,bert_131,bert_132,bert_133,bert_134,bert_135,bert_136,bert_137,bert_138,bert_139,bert_140,bert_141,bert_142,bert_143,bert_144,bert_145,bert_146,bert_147,bert_148,bert_149,bert_150,bert_151,bert_152,bert_153,bert_154,bert_155,bert_156,bert_157,bert_158,bert_159,bert_160,bert_161,bert_162,bert_163,bert_164,bert_165,bert_166,bert_167,bert_168,bert_169,bert_170,bert_171,bert_172,bert_173,bert_174,bert_175,bert_176,bert_177,bert_178,bert_179,bert_180,bert_181,bert_182,bert_183,bert_184,bert_185,bert_186,bert_187,bert_188,bert_189,bert_190,bert_191,bert_192,bert_193,bert_194,bert_195,bert_196,bert_197,bert_198,bert_199,bert_200,bert_201,bert_202,bert_203,bert_204,bert_205,bert_206,bert_207,bert_208,bert_209,bert_210,bert_211,bert_212,bert_213,bert_214,bert_215,bert_216,bert_217,bert_218,bert_219,bert_220,bert_221,bert_222,bert_223,bert_224,bert_225,bert_226,bert_227,bert_228,bert_229,bert_230,bert_231,bert_232,bert_233,bert_234,bert_235,bert_236,bert_237,bert_238,bert_239,bert_240,bert_241,bert_242,bert_243,bert_244,bert_245,bert_246,bert_247,bert_248,bert_249,bert_250,bert_251,bert_252,bert_253,bert_254,bert_255,bert_256,bert_257,bert_258,bert_259,bert_260,bert_261,bert_262,bert_263,bert_264,bert_265,bert_266,bert_267,bert_268,bert_269,bert_270,bert_271,bert_272,bert_273,bert_274,bert_275,bert_276,bert_277,bert_278,bert_279,bert_280,bert_281,bert_282,bert_283,bert_284,bert_285,bert_286,bert_287,bert_288,bert_289,bert_290,bert_291,bert_292,bert_293,bert_294,bert_295,bert_296,bert_297,bert_298,bert_299,bert_300,bert_301,bert_302,bert_303,bert_304,bert_305,bert_306,bert_307,bert_308,bert_309,bert_310,bert_311,bert_312,bert_313,bert_314,bert_315,bert_316,bert_317,bert_318,bert_319,bert_320,bert_321,bert_322,bert_323,bert_324,bert_325,bert_326,bert_327,bert_328,bert_329,bert_330,bert_331,bert_332,bert_333,bert_334,bert_335,bert_336,bert_337,bert_338,bert_339,bert_340,bert_341,bert_342,bert_343,bert_344,bert_345,bert_346,bert_347,bert_348,bert_349,bert_350,bert_351,bert_352,bert_353,bert_354,bert_355,bert_356,bert_357,bert_358,bert_359,bert_360,bert_361,bert_362,bert_363,bert_364,bert_365,bert_366,bert_367,bert_368,bert_369,bert_370,bert_371,bert_372,bert_373,bert_374,bert_375,bert_376,bert_377,bert_378,bert_379,bert_380,bert_381,bert_382,bert_383
0,Albania,2018-02-06,"On Feb. 6, 2018: An explosion occurred near th...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0,-0.003974,0.057839,-0.023864,0.013640,0.065623,-0.007908,-0.020057,0.019480,-0.048654,0.073403,0.068225,0.041850,0.035987,-0.016405,-0.000074,0.032849,-0.056953,-0.031694,-0.014113,-0.032365,-0.043954,0.065842,0.013307,-0.011615,4.197361e-02,0.031417,-0.001855,0.008511,0.012495,-0.031299,0.080728,-0.064527,-0.054790,-0.012554,0.105447,-0.015077,0.086048,0.020692,-0.004153,-0.001239,0.023915,-0.039077,0.011872,-0.004467,-0.069668,0.058318,-0.008851,-0.035183,0.042661,0.009080,-0.032043,0.024269,0.070337,-0.021088,0.003516,-0.127151,0.008281,-0.041446,0.018900,-0.009805,0.036528,0.039516,-0.011434,0.047036,0.082390,0.005486,0.024388,-0.019451,0.079658,0.014301,0.144788,-0.097717,0.050641,-0.118364,-0.044985,-0.047868,0.062575,-0.019625,-0.025143,0.001438,0.016911,-0.022094,-0.007903,-0.078122,0.030539,0.036594,-0.014598,0.049298,0.007395,0.046449,-0.053466,0.082889,0.078278,0.029377,0.128948,0.007307,-0.057149,0.023335,-0.045215,0.050690,0.024214,0.004338,-0.088420,-0.052494,-0.009898,0.002484,-0.011436,-0.050061,-0.065480,0.039495,0.016693,-0.051413,-0.004576,-0.086723,0.068047,0.011137,0.032452,0.044178,-0.115011,-0.011678,0.067976,-0.047684,-0.136307,0.077899,0.014479,0.077646,0.026334,-3.147346e-33,-0.026234,0.023108,-0.092774,0.026405,0.057635,-0.025354,-0.030205,0.015172,-0.008013,0.046502,-0.043412,-0.005759,-0.009346,-0.074648,-0.055954,-0.003518,0.094678,0.078539,-0.069042,-0.065113,-0.026858,0.077307,-0.041350,0.033855,-0.000448,0.107191,-0.004129,-0.015138,0.011550,-0.001668,-0.038118,0.094220,-0.031291,0.027039,0.025419,0.052956,-0.058790,-0.026118,-0.083981,-0.022227,-0.020715,0.044886,-0.028267,0.030331,-0.029364,0.005991,-0.050153,0.015295,0.093344,-0.124239,-0.062278,-0.023560,-0.046560,0.024296,-0.006347,0.035368,-0.019453,0.004203,0.121147,0.011106,0.053612,-0.028580,-0.051108,0.013440,0.023430,-0.163248,-0.008870,0.054727,0.077440,0.024042,-0.021310,0.071893,0.009177,-0.040104,-0.053439,-0.028155,-0.021401,0.001995,-0.039991,0.055632,0.056973,-0.011575,0.085981,0.009120,0.010197,0.007445,-0.028316,0.070571,-0.035675,0.055582,-0.022661,-0.059300,-0.002875,-0.024110,-0.094192,-6.260389e-35,-0.037051,-0.002435,-0.136722,-0.015011,-0.019059,0.054836,-0.096248,0.044026,-0.088108,-0.032832,0.028291,-0.029629,0.042096,0.027275,0.024384,-0.013323,0.073610,-0.017722,-0.036165,-0.015262,-0.058792,-0.050946,-0.062182,-0.015656,-0.023338,0.091023,0.009487,-0.003848,0.007564,0.032213,-0.068243,0.010477,-0.050486,0.064018,0.082674,0.131737,0.073984,0.014681,-0.012758,0.013677,-0.014848,0.119180,0.017881,0.077697,0.003850,-0.092583,0.009746,-0.012834,-0.092966,-0.006414,0.010616,0.012598,-0.060262,0.017759,0.028329,0.065112,-0.028188,-0.071840,-0.004413,-0.036444,-0.051421,0.039466,-0.104710,0.030383,-0.043166,-0.018697,-0.137920,-0.033723,-0.033543,0.032973,0.032377,0.045057,-0.041100,-0.069903,-0.097933,-0.018726,0.045977,0.017316,-0.044137,-0.039565,0.014395,-0.073067,-0.039135,0.035383,-0.009397,0.010610,0.121847,0.010316,0.050394,-0.054765,-0.058889,-0.010347,-0.042658,0.029264,0.000844,-3.420973e-08,-0.037028,0.043041,-0.058578,-0.023944,0.087618,0.022338,0.031391,0.020836,-0.059350,0.046708,0.001744,0.010415,0.004516,-0.087336,-0.034107,0.048590,-0.019609,-0.025593,-0.013644,-0.021393,-0.010601,0.019669,-0.036120,0.001708,-0.024377,0.115154,-0.042417,-0.007052,-0.001122,0.041312,-0.041821,0.016221,-0.070225,-0.072633,-0.036750,0.060024,0.085376,-0.015823,0.043469,-0.105231,-0.058401,-0.023530,0.019566,0.063028,0.024369,0.005474,-0.018613,-0.124406,-0.001913,-0.021623,-0.017519,0.011569,-0.021456,0.082288,0.067318,-0.079349,0.000961,0.002978,-0.014745,-0.019325,0.034108,0.009476,0.001720,0.029705
1,Albania,2018-02-06,"On Feb. 6, 2018: An explosion occurred in a bu...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0,0.022458,0.044925,0.039747,0.023597,0.021986,-0.057277,-0.000741,-0.016564,-0.013065,0.011654,0.075367,0.002932,0.014697,-0.024187,0.024339,0.045920,-0.035259,-0.086158,-0.046300,0.050278,0.025874,0.036318,-0.026445,0.058535,5.168880e-02,0.039180,0.051785,0.032888,0.016418,-0.016323,0.084501,-0.092532,-0.043348,0.021583,0.060729,0.023576,0.109246,0.018657,0.094654,0.019304,-0.013653,-0.046792,-0.013402,-0.058694,-0.035903,0.034241,0.029853,-0.060629,-0.005544,-0.007265,-0.001255,-0.007355,0.021900,-0.012923,0.047029,-0.152121,-0.065566,0.018007,0.026365,-0.008013,-0.019172,0.052784,-0.015974,-0.001819,0.018357,-0.042830,0.112364,-0.047795,0.064060,-0.003060,0.139628,-0.030296,0.089475,-0.155869,-0.066405,0.017289,-0.015769,-0.025513,-0.015169,0.001433,0.045130,-0.095726,0.001264,-0.035273,-0.007682,0.023317,-0.004433,0.103853,0.044245,0.021951,-0.039467,0.050709,0.001923,0.060226,0.062383,-0.003186,-0.074648,-0.047402,0.023564,0.060255,-0.081479,0.049157,0.024860,-0.030029,-0.048061,-0.032066,-0.088558,0.047331,-0.061371,-0.048401,0.007404,0.031496,0.037005,-0.085704,-0.004917,0.034947,0.051381,0.006035,-0.133035,0.026749,0.064886,-0.011124,-0.071255,0.056510,-0.045299,0.005778,0.012940,-1.818647e-33,0.019954,-0.029723,-0.018770,0.004586,0.065673,-0.018295,-0.089583,0.008691,-0.042817,0.003169,0.035436,-0.084591,0.002424,-0.005575,-0.015497,0.017372,0.082877,0.026761,-0.032651,-0.081321,-0.010087,0.009584,-0.046876,-0.000664,-0.005014,0.135297,0.084623,0.017568,-0.038358,0.012136,-0.001470,0.040910,-0.056165,0.022575,-0.052196,0.069872,-0.098263,-0.070733,-0.026580,-0.083625,-0.010334,-0.051873,-0.046064,0.028465,0.014491,0.071387,-0.040485,-0.019957,0.091019,-0.049079,-0.026829,-0.019726,-0.060967,0.113083,-0.012900,0.030261,-0.040700,-0.021349,0.103858,0.043410,0.082953,0.019610,-0.073645,0.023123,-0.039053,-0.156150,-0.048844,0.031608,0.029008,0.088554,0.026858,-0.014313,0.031634,0.040669,-0.090605,-0.075047,-0.026289,-0.005686,0.032952,0.115328,0.043085,-0.005072,0.077184,-0.000016,-0.040254,0.053180,0.000275,0.004817,-0.098255,0.041693,-0.103458,-0.065166,-0.038684,-0.025195,-0.064073,-1.527736e-33,-0.001738,0.016862,-0.063760,0.017518,-0.025406,0.052023,-0.039932,0.067940,-0.104137,-0.022006,-0.017741,0.027999,-0.008051,0.048040,0.057073,-0.035344,0.078645,-0.037330,-0.012303,0.015337,-0.029900,-0.015614,-0.030991,-0.033484,0.046835,0.029873,0.013200,-0.020094,0.011075,0.025603,-0.066332,0.048138,-0.024940,0.068465,0.042651,0.063250,0.080498,0.010561,0.005590,-0.052848,-0.022848,0.109099,-0.009273,0.150805,0.001811,0.002574,0.006978,-0.039276,-0.010854,-0.014891,-0.003633,0.066532,-0.056640,-0.047150,0.059404,0.002853,-0.078229,-0.100095,-0.075013,-0.037188,-0.039663,0.030284,-0.081052,0.045197,-0.026825,-0.000082,-0.055193,-0.059299,0.015467,0.018737,0.023148,0.032661,-0.092749,-0.036420,-0.050406,-0.004661,-0.039336,0.063419,-0.047424,0.001697,0.124880,0.003846,-0.056862,0.043533,0.035280,0.000334,0.069150,0.017337,0.040805,-0.052717,-0.055407,0.041737,-0.014309,0.044009,0.023734,-3.336655e-08,-0.055294,0.029655,-0.019357,-0.054427,0.038458,-0.028767,0.054250,0.050082,-0.068724,0.033226,-0.040695,-0.012022,-0.024501,0.056286,-0.107818,0.017007,-0.025989,-0.049592,-0.014533,-0.027511,0.006717,0.012913,0.023257,0.020099,-0.001000,0.045621,-0.037539,0.018266,-0.063276,0.056635,0.018603,-0.003802,-0.058170,-0.033025,-0.073722,0.061082,0.021350,0.011561,-0.033427,-0.068441,-0.025510,-0.075268,0.108100,0.022114,0.019656,0.019791,-0.082260,-0.047007,0.002124,0.037105,0.053133,0.002453,0.002446,0.070103,-0.025172,-0.050843,-0.008566,-0.047572,0.050793,-0.062165,0.077797,-0.033391,-0.032597,0.031741
2,Albania,2018-02-06,"On Feb. 6, 2018: An explosion with TNT occurre...",0,0,1,0,0,0,0,0.0,0,0,1,0,0,0,0,-0.032216,0.053874,-0.056166,-0.003603,0.021312,-0.098377,0.110736,0.044709,0.021153,-0.062096,0.082193,0.058947,0.051996,0.063790,0.018632,-0.060688,-0.021372,-0.067203,-0.074206,-0.045537,-0.010669,0.055088,0.044602,0.071709,1.806997e-02,0.023234,0.041136,0.004978,-0.000958,0.010099,0.041605,-0.056510,-0.132762,-0.011153,0.093561,0.032871,0.012586,0.009395,0.086657,-0.010871,0.035074,-0.064874,-0.041797,-0.011858,0.005694,0.016617,0.036958,-0.048389,0.062907,0.024024,-0.030343,-0.016572,0.062761,-0.055159,-0.014654,-0.090104,0.048735,-0.000980,-0.004069,-0.017716,-0.022554,0.041413,-0.013115,-0.013081,0.030215,0.026021,0.123625,-0.005400,0.085032,-0.079598,0.139927,-0.042274,0.052853,0.024887,-0.050489,-0.054840,0.053223,0.003574,-0.065070,0.017636,0.069406,-0.053528,-0.013952,-0.039200,0.016737,0.042620,-0.036925,0.044433,0.051712,0.069531,0.013950,0.070363,0.072553,-0.050869,0.083021,-0.009312,-0.017178,-0.042392,-0.037847,0.066302,0.001091,0.021275,-0.091934,0.002780,0.001554,-0.022783,-0.075521,-0.010696,-0.036528,0.014198,0.019495,-0.005658,0.036165,-0.072517,0.011950,0.051181,0.009948,0.062475,-0.057900,-0.044082,-0.019273,0.055586,-0.110871,0.050624,-0.047085,0.049521,-0.010151,-1.069184e-33,-0.028955,0.090904,-0.018229,0.018074,0.029905,0.030538,-0.074290,-0.020605,-0.006093,-0.052580,-0.079293,-0.137680,-0.015564,-0.043158,-0.015218,-0.015010,0.037509,0.064440,-0.003304,-0.081841,-0.053136,0.010307,-0.015127,0.003830,-0.043875,0.125517,-0.000901,0.014148,0.011664,0.010236,-0.036757,0.044524,-0.033392,-0.051419,0.020623,0.013469,-0.112441,-0.000648,-0.027332,-0.019311,-0.042695,0.039649,-0.031800,0.074959,-0.005966,0.011001,-0.071797,0.081037,0.039985,-0.166182,-0.061758,-0.019329,0.029665,-0.022348,-0.006124,0.051656,0.017053,-0.027936,0.121063,0.046630,0.137653,0.025958,-0.067320,0.098932,0.007247,-0.047298,-0.049705,-0.003181,0.062446,0.030584,-0.028966,0.013010,0.031667,-0.028507,-0.067317,0.033447,-0.023184,-0.015531,-0.029666,0.031381,-0.036212,-0.046586,0.175049,0.031524,-0.054545,0.054114,-0.009669,-0.017347,0.003902,0.072044,-0.067433,-0.065439,0.039303,-0.018250,-0.028274,-1.253012e-33,0.033332,0.073026,-0.067266,-0.043739,-0.024321,-0.014943,-0.061833,0.015732,-0.047855,0.027272,0.031972,-0.025044,0.008855,0.030738,0.025241,0.079946,0.082186,0.029552,-0.019057,-0.013859,-0.088886,-0.051259,-0.043192,0.017137,-0.006712,0.011062,0.063755,-0.019905,0.003332,-0.030116,-0.014549,-0.002889,-0.023317,0.079435,0.013898,0.094082,0.082749,-0.015988,0.053193,-0.010209,0.012013,0.110486,-0.014054,0.125409,-0.067660,-0.028807,0.046105,-0.020963,-0.022979,-0.127542,-0.010920,-0.000647,-0.010175,-0.020692,0.030983,-0.020611,0.001122,-0.028628,-0.005711,-0.091748,-0.003815,0.012212,-0.049136,0.026136,-0.050040,-0.043103,-0.059245,-0.030081,0.020096,-0.054962,0.086835,-0.033494,-0.037950,-0.033078,-0.084185,0.018338,-0.035759,0.048511,-0.022433,-0.035555,0.081937,-0.047099,-0.108165,0.010090,0.018965,-0.002057,0.072207,0.018704,0.052470,-0.048312,-0.063123,-0.006523,-0.001362,0.043195,0.098210,-3.641112e-08,0.045453,0.018052,-0.040895,0.014874,0.001484,-0.012992,0.066313,0.041436,-0.042243,0.022308,-0.125578,-0.039349,-0.011880,-0.015208,-0.077135,0.080007,-0.058281,0.053638,-0.020364,-0.045471,0.051410,0.003951,0.027462,-0.034412,-0.002276,0.014246,-0.006698,0.013507,-0.014744,-0.020452,-0.021094,-0.058886,-0.066065,-0.074635,-0.056912,0.064781,0.033201,-0.016392,0.028645,-0.068931,-0.125199,-0.030885,-0.023251,0.045043,-0.004473,-0.027724,-0.014020,-0.018801,-0.028018,0.034327,0.039256,0.024588,0.047017,0.052051,0.015565,-0.013258,-0.032057,-0.046443,0.006573,-0.009546,0.098966,-0.044275,0.051180,-0.039614
3,Albania,2018-02-12,"On Feb. 12, 2018: National theater artists for...",0,0,0,0,1,0,0,0.0,1,0,0,0,0,1,0,0.041451,0.060823,0.027797,0.038895,0.028736,0.116989,0.043393,-0.144543,0.005008,-0.022823,-0.025945,0.020813,0.047004,0.038058,0.007332,-0.007054,0.095035,-0.025240,0.001392,0.038195,-0.056347,-0.061297,-0.054216,0.029580,-2.965478e-02,-0.068390,0.009031,0.013045,0.017465,-0.002805,-0.063461,-0.005919,-0.070654,0.063439,0.060583,0.050999,0.018804,-0.025747,-0.002985,0.000871,0.020348,-0.011700,-0.037369,0.020175,0.021169,-0.000382,-0.080777,-0.005063,-0.020549,0.005990,-0.019516,0.018712,0.037562,-0.072300,-0.000741,-0.078480,0.061870,0.034056,0.066155,0.049109,-0.016393,-0.025216,-0.020070,0.030134,0.036283,0.040564,-0.002451,0.017556,0.093472,-0.009130,0.024671,-0.023546,0.047087,-0.090161,-0.001429,0.004939,-0.076150,-0.034233,0.020590,-0.121122,0.114617,-0.070202,-0.024921,-0.011817,0.016917,0.023862,-0.043784,0.029216,0.037443,0.034070,-0.002062,0.010413,0.011631,0.058735,0.133393,-0.077042,-0.019520,-0.024967,0.014274,0.054980,0.052875,0.042876,0.032358,-0.064551,-0.044932,-0.046790,0.007036,-0.020154,-0.150381,0.041239,0.021658,0.062482,0.045678,0.018744,0.054506,0.085606,-0.020181,-0.023039,0.019189,-0.036327,-0.016894,0.026284,-0.024959,0.029487,-0.080383,-0.010991,-0.049207,-3.074741e-33,-0.009452,-0.030238,-0.010895,-0.032407,0.014785,-0.053062,-0.048056,0.003950,0.060819,-0.038846,0.074095,-0.073922,0.051134,-0.023727,-0.023354,0.035194,0.005876,0.049993,-0.030997,0.015893,0.002115,0.011289,-0.036656,0.083750,-0.108687,0.105934,-0.082867,0.017116,0.025141,0.001015,-0.041089,0.014943,0.083194,0.043857,0.089624,-0.047682,0.029595,-0.026732,-0.020712,-0.047231,-0.029018,0.037618,-0.046695,0.040779,-0.029102,0.054160,-0.022435,-0.042603,0.022358,0.046287,-0.036498,0.147584,-0.042664,-0.024653,0.023112,-0.013923,-0.039030,-0.049137,0.029454,-0.144653,0.066934,0.122300,0.027675,0.045701,0.019015,-0.053799,-0.010790,0.007960,0.063857,-0.045075,-0.067716,0.021940,0.020809,0.000665,-0.022583,-0.025053,0.027059,-0.021558,0.058503,-0.023356,0.021164,0.030915,0.019868,-0.008584,-0.008799,-0.020034,-0.018256,-0.019120,0.009290,0.058927,0.043893,-0.017186,-0.054530,0.052617,-0.015388,4.367132e-34,0.099784,0.013698,-0.030195,-0.027949,-0.016646,-0.101055,-0.073350,0.068985,0.112653,0.040611,0.005349,-0.013974,0.045824,0.027575,-0.019315,-0.135718,0.028132,0.077897,-0.003753,0.023674,-0.006607,-0.027474,-0.013781,-0.083889,-0.032519,0.094881,0.085951,0.025317,-0.088239,-0.009209,0.059284,-0.025226,-0.005227,0.016171,0.025344,-0.017794,0.133870,-0.023943,-0.105041,-0.031904,-0.040052,0.073717,-0.057207,0.135782,-0.053970,0.001268,-0.017856,0.000620,-0.035258,-0.045023,-0.045228,-0.010970,0.060224,-0.160315,-0.002745,-0.027717,-0.009936,-0.023926,0.028300,0.080878,-0.011485,0.014723,-0.108740,-0.141163,0.010661,0.047984,-0.074077,0.095326,0.016158,0.054364,0.062044,-0.005749,0.005071,0.049897,-0.065684,-0.026327,0.062161,0.005239,-0.015408,-0.019706,0.016647,-0.047994,-0.048874,0.009182,0.021023,0.146561,-0.001915,-0.045705,-0.064043,0.011443,0.024232,-0.058137,0.055365,-0.010568,-0.017417,-3.614149e-08,-0.074953,0.012596,0.004302,-0.035575,0.055553,-0.017649,-0.016342,-0.028112,0.030373,0.038392,-0.004935,-0.065183,0.053733,-0.037269,-0.040340,-0.029306,0.009488,-0.060725,-0.087625,-0.042691,-0.052400,-0.019189,0.038741,-0.019295,-0.030219,0.031830,-0.051026,-0.027279,-0.069179,0.111247,-0.092308,0.017067,-0.039225,-0.013072,-0.029676,0.040501,-0.009389,-0.061023,0.036908,-0.125279,-0.007119,0.010780,0.052914,0.024843,0.004467,0.003946,0.061856,0.039128,-0.024055,0.012994,-0.076158,-0.060181,-0.050613,0.043946,0.030683,-0.042630,0.020646,0.084593,-0.006898,0.062060,-0.020137,-0.013739,-0.018947,0.014590

In [41]:
df["week"] = df["event_date"].dt.to_period("W")

bert_cols = [cols for cols in df.columns if cols.startswith("bert_")]
actor_cols = [cols for cols in df.columns if cols.startswith("actor_")]
event_type_cols = [cols for cols in df.columns if cols.startswith("event_type_")]

weekly_df = df.groupby(["country", "week"]).agg(
    {
    "fatalities": "sum",
    **{col: "sum" for col in actor_cols},
    **{col: "sum" for col in event_type_cols},
    **{col: "mean" for col in bert_cols}
    }
).reset_index()

In [42]:
# embeddings_df.to_csv("/content/embeddings_df.csv", index = False)

In [43]:
weekly_df

,country,week,fatalities,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,bert_0,bert_1,bert_2,bert_3,bert_4,bert_5,bert_6,bert_7,bert_8,bert_9,bert_10,bert_11,bert_12,bert_13,bert_14,bert_15,bert_16,bert_17,bert_18,bert_19,bert_20,bert_21,bert_22,bert_23,bert_24,bert_25,bert_26,bert_27,bert_28,bert_29,bert_30,bert_31,bert_32,bert_33,bert_34,bert_35,bert_36,bert_37,bert_38,bert_39,bert_40,bert_41,bert_42,bert_43,bert_44,bert_45,bert_46,bert_47,bert_48,bert_49,bert_50,bert_51,bert_52,bert_53,bert_54,bert_55,bert_56,bert_57,bert_58,bert_59,bert_60,bert_61,bert_62,bert_63,bert_64,bert_65,bert_66,bert_67,bert_68,bert_69,bert_70,bert_71,bert_72,bert_73,bert_74,bert_75,bert_76,bert_77,bert_78,bert_79,bert_80,bert_81,bert_82,bert_83,bert_84,bert_85,bert_86,bert_87,bert_88,bert_89,bert_90,bert_91,bert_92,bert_93,bert_94,bert_95,bert_96,bert_97,bert_98,bert_99,bert_100,bert_101,bert_102,bert_103,bert_104,bert_105,bert_106,bert_107,bert_108,bert_109,bert_110,bert_111,bert_112,bert_113,bert_114,bert_115,bert_116,bert_117,bert_118,bert_119,bert_120,bert_121,bert_122,bert_123,bert_124,bert_125,bert_126,bert_127,bert_128,bert_129,bert_130,bert_131,bert_132,bert_133,bert_134,bert_135,bert_136,bert_137,bert_138,bert_139,bert_140,bert_141,bert_142,bert_143,bert_144,bert_145,bert_146,bert_147,bert_148,bert_149,bert_150,bert_151,bert_152,bert_153,bert_154,bert_155,bert_156,bert_157,bert_158,bert_159,bert_160,bert_161,bert_162,bert_163,bert_164,bert_165,bert_166,bert_167,bert_168,bert_169,bert_170,bert_171,bert_172,bert_173,bert_174,bert_175,bert_176,bert_177,bert_178,bert_179,bert_180,bert_181,bert_182,bert_183,bert_184,bert_185,bert_186,bert_187,bert_188,bert_189,bert_190,bert_191,bert_192,bert_193,bert_194,bert_195,bert_196,bert_197,bert_198,bert_199,bert_200,bert_201,bert_202,bert_203,bert_204,bert_205,bert_206,bert_207,bert_208,bert_209,bert_210,bert_211,bert_212,bert_213,bert_214,bert_215,bert_216,bert_217,bert_218,bert_219,bert_220,bert_221,bert_222,bert_223,bert_224,bert_225,bert_226,bert_227,bert_228,bert_229,bert_230,bert_231,bert_232,bert_233,bert_234,bert_235,bert_236,bert_237,bert_238,bert_239,bert_240,bert_241,bert_242,bert_243,bert_244,bert_245,bert_246,bert_247,bert_248,bert_249,bert_250,bert_251,bert_252,bert_253,bert_254,bert_255,bert_256,bert_257,bert_258,bert_259,bert_260,bert_261,bert_262,bert_263,bert_264,bert_265,bert_266,bert_267,bert_268,bert_269,bert_270,bert_271,bert_272,bert_273,bert_274,bert_275,bert_276,bert_277,bert_278,bert_279,bert_280,bert_281,bert_282,bert_283,bert_284,bert_285,bert_286,bert_287,bert_288,bert_289,bert_290,bert_291,bert_292,bert_293,bert_294,bert_295,bert_296,bert_297,bert_298,bert_299,bert_300,bert_301,bert_302,bert_303,bert_304,bert_305,bert_306,bert_307,bert_308,bert_309,bert_310,bert_311,bert_312,bert_313,bert_314,bert_315,bert_316,bert_317,bert_318,bert_319,bert_320,bert_321,bert_322,bert_323,bert_324,bert_325,bert_326,bert_327,bert_328,bert_329,bert_330,bert_331,bert_332,bert_333,bert_334,bert_335,bert_336,bert_337,bert_338,bert_339,bert_340,bert_341,bert_342,bert_343,bert_344,bert_345,bert_346,bert_347,bert_348,bert_349,bert_350,bert_351,bert_352,bert_353,bert_354,bert_355,bert_356,bert_357,bert_358,bert_359,bert_360,bert_361,bert_362,bert_363,bert_364,bert_365,bert_366,bert_367,bert_368,bert_369,bert_370,bert_371,bert_372,bert_373,bert_374,bert_375,bert_376,bert_377,bert_378,bert_379,bert_380,bert_381,bert_382,bert_383
0,Albania,2018-02-05/2018-02-11,0,0.0,0,0,3,0,0,0,0,0,3,0,0,0,0,-0.004577,0.052213,-0.013428,0.011211,0.036307,-0.054521,0.029979,0.015875,-0.013522,0.007654,0.075262,0.034576,0.034227,0.007733,0.014299,0.006027,-0.037861,-0.061685,-0.044873,-0.009208,-0.009583,0.052416,0.010488,0.039543,0.037244,0.031277,0.030355,0.015459,0.009318,-0.012508,0.068945,-0.071190,-0.076967,-0.000708,0.086579,0.013790,0.069294,0.016248,0.059053,0.002398,0.015112,-0.050247,-0.014442,-0.025006,-0.033292,0.036392,0.019320,-0.048067,0.033341,0.008613,-0.021214,0.000114,0.051666,-0.029723,0.011964,-0.123125,-0.002850,-0.008140,0.013732,-0.011845,-0.001733,0.044571,-0.013507,0.010712,0.043654,-0.003774,0.086792,-0.024215,0.076250,-0.022786,0.141448,-0.056762,0.064323,-0.083115,-0.053960,-0.028473,0.033343,-0.013855,-0.035127,0.006836,0.043815,-0.057116,-0.006864,-0.050865,0.013198,0.034177,-0.018652,0.065861,0.034450,0.045977,-0.026328,0.067987,0.050918,0.012911,0.091451,-0.001730,-0.049658,-0.022153,-0.019833,0.059082,-0.018725,0.024923,-0.051831,-0.026581,-0.018802,-0.017455,-0.058505,-0.004476,-0.054460,0.001764,0.014530,-0.008525,0.022865,-0.081648,0.025027,0.032422,0.031260,0.037562,-0.101982,-0.009670,0.037863,-0.001074,-0.106144,0.061678,-0.025968,0.044315,0.009708,-2.011726e-33,-0.011745,0.028096,-0.043258,0.016355,0.051071,-0.004370,-0.064693,0.001086,-0.018974,-0.000970,-0.029089,-0.076010,-0.007495,-0.041127,-0.028890,-0.000385,0.071688,0.056580,-0.034999,-0.076092,-0.030027,0.032400,-0.034451,0.012340,-0.016446,0.122668,0.026531,0.005526,-0.005048,0.006901,-0.025448,0.059884,-0.040282,-0.000602,-0.002051,0.045432,-0.089832,-0.032500,-0.045964,-0.041721,-0.024582,0.010887,-0.035377,0.044585,-0.006946,0.029460,-0.054145,0.025458,0.074783,-0.113167,-0.050288,-0.020872,-0.025954,0.038343,-0.008457,0.039095,-0.014366,-0.015027,0.115356,0.033715,0.091406,0.005663,-0.064024,0.045165,-0.002792,-0.122232,-0.035806,0.027718,0.056298,0.047727,-0.007806,0.023530,0.024159,-0.009314,-0.070454,-0.023251,-0.023625,-0.006407,-0.012235,0.067447,0.021282,-0.021077,0.112738,0.013543,-0.028201,0.038246,-0.012570,0.019347,-0.043342,0.056439,-0.064517,-0.063302,-0.000752,-0.022519,-0.062180,-9.477841e-34,-0.001819,0.029151,-0.089249,-0.013744,-0.022928,0.030638,-0.066004,0.042566,-0.080033,-0.009188,0.014174,-0.008891,0.014300,0.035351,0.035566,0.010426,0.078147,-0.008500,-0.022509,-0.004595,-0.059193,-0.039273,-0.045455,-0.010668,0.005595,0.043986,0.028814,-0.014616,0.007324,0.009233,-0.049708,0.018576,-0.032914,0.070639,0.046408,0.096356,0.079077,0.003085,0.015342,-0.016460,-0.008561,0.112922,-0.001815,0.117971,-0.020666,-0.039605,0.020943,-0.024357,-0.042266,-0.049616,-0.001312,0.026161,-0.042359,-0.016695,0.039572,0.015784,-0.035098,-0.066855,-0.028379,-0.055127,-0.031633,0.027321,-0.078300,0.033905,-0.040010,-0.020627,-0.084120,-0.041035,0.000673,-0.001084,0.047453,0.014741,-0.057267,-0.046467,-0.077508,-0.001683,-0.009706,0.043082,-0.037998,-0.024474,0.073737,-0.038774,-0.068054,0.029669,0.014949,0.002962,0.087735,0.015452,0.047890,-0.051931,-0.059139,0.008289,-0.019443,0.038822,0.040929,-3.466246e-08,-0.015623,0.030250,-0.039610,-0.021166,0.042520,-0.006474,0.050651,0.037452,-0.056772,0.034081,-0.054843,-0.013652,-0.010622,-0.015420,-0.073020,0.048535,-0.034626,-0.007183,-0.016180,-0.031458,0.015842,0.012178,0.004866,-0.004202,-0.009218,0.058340,-0.028885,0.008240,-0.026381,0.025832,-0.014771,-0.015489,-0.064820,-0.060097,-0.055794,0.061962,0.046642,-0.006885,0.012895,-0.080868,-0.069703,-0.043228,0.034805,0.043395,0.013184,-0.000820,-0.038298,-0.063405,-0.009269,0.016603,0.024957,0.012870,0.009336,0.068147,0.019237,-0.047817,-0.013221,-0.030345,0.014207,-0.030345,0.070290,-0.022730,0.006768,0.007278
1,Albania,2018-02-12/2018-02-18,0,0.0,1,0,0,0,0,1,0,0,0,0,1,0,0,0.041451,0.060823,0.027797,0.038895,0.028736,0.116989,0.043393,-0.144543,0.005008,-0.022823,-0.025945,0.020813,0.047004,0.038058,0.007332,-0.007054,0.095035,-0.025240,0.001392,0.038195,-0.056347,-0.061297,-0.054216,0.029580,-0.029655,-0.068390,0.009031,0.013045,0.017465,-0.002805,-0.063461,-0.005919,-0.070654,0.063439,0.060583,0.050999,0.018804,-0.025747,-0.002985,0.000871,0.020348,-0.011700,-0.037369,0.020175,0.021169,-0.000382,-0.080777,-0.005063,-0.020549,0.005990,-0.019516,0.018712,0.037562,-0.072300,-0.000741,-0.078480,0.061870,0.034056,0.066155,0.049109,-0.016393,-0.025216,-0.020070,0.030134,0.036283,0.040564,-0.002451,0.017556,0.093472,-0.009130,0.024671,-0.023546,0.047087,-0.090161,-0.001429,0.004939,-0.076150,-0.034233,0.020590,-0.121122,0.114617,-0.070202,-0.024921,-0.011817,0.016917,0.023862,-0.043784,0.029216,0.037443,0.034070,-0.002062,0.010413,0.011631,0.058735,0.133393,-0.077042,-0.019520,-0.024967,0.014274,0.054980,0.052875,0.042876,0.032358,-0.064551,-0.044932,-0.046790,0.007036,-0.020154,-0.150381,0.041239,0.021658,0.062482,0.045678,0.018744,0.054506,0.085606,-0.020181,-0.023039,0.019189,-0.036327,-0.016894,0.026284,-0.024959,0.029487,-0.080383,-0.010991,-0.049207,-3.074741e-33,-0.009452,-0.030238,-0.010895,-0.032407,0.014785,-0.053062,-0.048056,0.003950,0.060819,-0.038846,0.074095,-0.073922,0.051134,-0.023727,-0.023354,0.035194,0.005876,0.049993,-0.030997,0.015893,0.002115,0.011289,-0.036656,0.083750,-0.108687,0.105934,-0.082867,0.017116,0.025141,0.001015,-0.041089,0.014943,0.083194,0.043857,0.089624,-0.047682,0.029595,-0.026732,-0.020712,-0.047231,-0.029018,0.037618,-0.046695,0.040779,-0.029102,0.054160,-0.022435,-0.042603,0.022358,0.046287,-0.036498,0.147584,-0.042664,-0.024653,0.023112,-0.013923,-0.039030,-0.049137,0.029454,-0.144653,0.066934,0.122300,0.027675,0.045701,0.019015,-0.053799,-0.010790,0.007960,0.063857,-0.045075,-0.067716,0.021940,0.020809,0.000665,-0.022583,-0.025053,0.027059,-0.021558,0.058503,-0.023356,0.021164,0.030915,0.019868,-0.008584,-0.008799,-0.020034,-0.018256,-0.019120,0.009290,0.058927,0.043893,-0.017186,-0.054530,0.052617,-0.015388,4.367132e-34,0.099784,0.013698,-0.030195,-0.027949,-0.016646,-0.101055,-0.073350,0.068985,0.112653,0.040611,0.005349,-0.013974,0.045824,0.027575,-0.019315,-0.135718,0.028132,0.077897,-0.003753,0.023674,-0.006607,-0.027474,-0.013781,-0.083889,-0.032519,0.094881,0.085951,0.025317,-0.088239,-0.009209,0.059284,-0.025226,-0.005227,0.016171,0.025344,-0.017794,0.133870,-0.023943,-0.105041,-0.031904,-0.040052,0.073717,-0.057207,0.135782,-0.053970,0.001268,-0.017856,0.000620,-0.035258,-0.045023,-0.045228,-0.010970,0.060224,-0.160315,-0.002745,-0.027717,-0.009936,-0.023926,0.028300,0.080878,-0.011485,0.014723,-0.108740,-0.141163,0.010661,0.047984,-0.074077,0.095326,0.016158,0.054364,0.062044,-0.005749,0.005071,0.049897,-0.065684,-0.026327,0.062161,0.005239,-0.015408,-0.019706,0.016647,-0.047994,-0.048874,0.009182,0.021023,0.146561,-0.001915,-0.045705,-0.064043,0.011443,0.024232,-0.058137,0.055365,-0.010568,-0.017417,-3.614149e-08,-0.074953,0.012596,0.004302,-0.035575,0.055553,-0.017649,-0.016342,-0.028112,0.030373,0.038392,-0.004935,-0.065183,0.053733,-0.037269,-0.040340,-0.029306,0.009488,-0.060725,-0.087625,-0.042691,-0.052400,-0.019189,0.038741,-0.019295,-0.030219,0.031830,-0.051026,-0.027279,-0.069179,0.111247,-0.092308,0.017067,-0.039225,-0.013072,-0.029676,0.040501,-0.009389,-0.061023,0.036908,-0.125279,-0.007119,0.010780,0.052914,0.024843,0.004467,0.003946,0.061856,0.039128,-0.024055,0.012994,-0.076158,-0.060181,-0.050613,0.043946,0.030683,-0.042630,0.020646,0.084593,-0.006898,0.062060,-0.020137,-0.013739,-0.018947,0.014590
2,Albania,2018-03-19/2018-03-25,0,0.0,0,0,0,0,0,1,1,0,0,0,1,0,0,-0.018453,0.052927,0.011251,0.020172,0.065999,-0.051773,0.062296,0.009563,-0.113556,-0.064120,0.009259,0.002009,0.026507,0.047409,0.028867,0.049510,0.028101,0.005299,-0.013721,-0.051474,-0.000977,-0.013761,0.005384,0.092357,-0.012972,0.029609,-0.011506,0.000973,0.053442,0.018569,0.003195,0.059401,-0.018027,0.023050,0.064879,0.024494,0.016830,-0.051605,0.028352,-0.070816,0.057124,-0.106669,-0.002765,-0.027874,-0.012736,0.026937,0.124872,0.021935,0.009001,-0.072077,0.038181,-0.064962,0.087381,-0.078257,-0.037927,-0.035481,0.035432,-0.014534,0.035582,0.010034,-0.046787,-0.015344,-0.014257,0.028058,0.076939,0.015229,0.044019,-0.022918,0.041068,-0.062267,0.118254,-0.047955,-0.014641,-0.033109,-0.003524,0.025747,-0.026422,0.067735,0.048358,-0.084522,0.000716,-0.070297,0.025193,0.000914,0.058191,-0.025054,-0.078287,0.096116,0.015524,-0.027563,0.013122,0.033097,-0.016512,0.006724,0.029161,-0.039187,0.081412,0.015431,0.016750,0.105479,0.082665,0.088724,-0.098869,-0.015576,-0.001046,-0.014664,-0.041791,-0.031852,-0.053181,0.026235,0.084765,-0.062941,0.039236,-0.026087,-0.028293,0.049044,0.021950,0.074302,-0.026627,0.002631,-0.034115,0.108023,-0.088860,-0.031203,0.043121,0.073293,-0.026330,-3.352946e-33,-0.021172,-0.022597,-0.024244,0.003052,0.004928,0.077536,-0.021534,-0.045822,0.021700,-0.044645,-0.031295,0.016259,0.082646,-0.079494,-0.060343,-0.058516,0.055189,-0.040823,-0.026373,0.034217,0.019618,-0.057268,-0.076948,0.073462,-0.004414,0.078842,0.011944,-0.021533,0.075395,0.010733,-0.025313,-0.004021,0.030802,-0.004209,0.009507,0.053282,-0.011085,-0.040276,-0.032634,-0.080348,-0.058274,0.016862,-0.036719,-0.030278,0.007472,0.042508,-0.034460,0.045357,-0.027230,-0.102143,-0.013642,0.039330,-0.040138,-0.042506,0.031521,0.051383,-0.008946,0.000213,0.037613,0.008493,0.065166,0.053841,-0.089763,0.081435,0.002805,0.043121,-0.006951,0.065625,-0.020265,0.047533,0.039821,0.052767,-0.057471,0.034408,-0.067851,0.038544,-0.030568,-0.056872,-0.058488,0.017126,-0.016934,-0.042631,0.059475,0.010564,0.017006,-0.014920,-0.002574,-0.013561,-0.003545,-0.008297,-0.070841,-0.032960,0.072630,0.069293,-0.041905,1.225291e-33,0.006462,0.078167,-0.033471,-0.032881,-0.021509,-0.012015,0.069357,-0.063783,-0.005132,0.089593,0.014207,-0.073796,-0.021672,0.041658,-0.034478,0.058114,-0.034983,0.133161,0.046450,0.050410,-0.169154,0.041632,-0.046965,0.006916,-0.090031,-0.014449,0.026591,-0.084542,-0.002047,-0.052321,-0.002616,-0.066032,-0.100077,-0.014290,0.013822,0.071968,0.072685,-0.042753,0.044093,0.040663,-0.055346,0.028916,-0.023730,0.121509,-0.106606,0.010908,0.008294,-0.012080,-0.095867,-0.128990,-0.046346,0.040227,-0.032837,-0.019078,-0.043554,-0.068490,-0.045157,0.062852,-0.099851,-0.039309,0.022236,-0.034339,-0.063028,0.035294,-0.005852,-0.028786,-0.059838,0.047496,0.080160,0.032169,0.058041,-0.040513,-0.068345,0.036371,-0.018616,0.045799,-0.004805,0.096160,0.060010,0.012963,0.046443,-0.022991,-0.042562,0.015805,0.040740,-0.011635,0.094015,0.033484,0.023490,-0.028600,0.019161,-0.001635,-0.044569,0.053521,0.058882,-3.471376e-08,0.035877,-0.021867,-0.069353,0.011828,-0.006819,0.000621,0.048845,-0.075696,-0.044046,0.009649,-0.108144,-0.127051,-0.088814,-0.089155,0.031260,0.067246,-0.063803,0.017089,-0.013263,-0.014543,-0.003256,-0.036412,-0.010492,0.045092,-0.100376,-0.004301,0.035076,-0.047879,-0.010855,0.026767,-0.036052,-0.010943,-0.017405,-0.078519,0.053022,0.061384,-0.008857,-0.035908,0.100860,-0.030545,-0.143775,-0.007375,-0.003182,0.008481,0.033077,-0.037335,0.021966,0.010896,-0.013124,-0.054638,0.001646,-0.057087,0.114474,0.068058,0.038387,0.069379,-0.003454,-0.008091,-0.078032,-0.015307,0.084890,0.017045,0.025673,0.005045
3,Albania,2018-03-26/2018-04-01,0,0.0,0,0,0,0,0,1,1,0,0,0,1,0,0,-0.004325,0.112572,0.034390,0.048747,0.001848,-0.011215,0.051443,-0.043494,0.013743,0.050167,0.029741,-0.034164,-0.036019,0.024852,-0.044420,-0.015735,-0.011400,0.037452,-0.116040,-0.058135,-0.030423,-0.014305,0.085072,0.063342,-0.060228,-0.029572,0.027218,0.058163,0.074068,-0.039196,0.000733,-0.041599,-0.161995,0.025801,0.005084,-0.042484,0.007576,-0.006029,0.015606,-0.093400,0.107153,-0.054887,-0.001222,-0.031474,0.100128,0.000936,0.036870,0.018025,0.034814,-0.035714,0.102880,0.002432,0.074001,-0.055518,0.017692,-0.164174,0.003127,0.010980,0.059872,0.029300,0.005603,-0.010869,-0.004602,0.006804,-0.067891,0.003758,0.039071,0.003822,0.061335,0.068696,0.101056,0.006798,0.012352,-0.004573,0.024197,0.002292,-0.037068,0.043765,-0.081284,-0.072697,0.071694,-0.074501,-0.041528,0.037191,0.021516,-0.037580,-0.057895,0.029432,0.073484,0.036809,0.050851,0.117619,0.073755,-0.007731,0.078631,-0.043055,0.027007,0.007261,-0.028300,0.094205,0.063816,0.016874,-0.045311,0.001096,0.006493,-0.015744,-0.070743,-0.120170,-0.078065,0.028470,0.029830,-0.035070,-0.013348,-0.042663,0.009943,-0.038075,0.002882,0.036418,0.038676,0.058872,-0.032859,0.056184,-0.137213,0.053919,0.070694,0.058964,-0.079175,1.263598e-33,-0.018151,-0.042820,-0.019049,-0.006399,0.040395,-0.072112,-0.022857,-0.068136,0.033150,-0.088185,-0.101825,-0.012766,0.020287,-0.111354,0.029816,0.022917,-0.004561,0.001024,-0.064890,0.014494,-0.015441,-0.098172,-0.012492,0.062362,-0.076621,0.034083,-0.005399,-0.033050,0.055076,0.021863,-0.063386,0.007444,0.046309,-0.008531,-0.078606,0.061773,-0.002932,-0.030312,-0.121996,-0.023254,-0.030921,-0.024505,-0.007043,0.008389,0.054433,0.007593,-0.087408,0.019825,-0.003193,-0.033524,-0.039160,-0.012749,0.019856,-0.012076,-0.015576,0.085884,-0.012364,-0.021327,0.037676,0.030731,0.032516,0.007250,-0.044575,0.047720,0.038057,-0.009123,-0.031353,0.081198,-0.008741,-0.002456,-0.001462,0.061237,-0.074113,0.009071,-0.043379,0.009880,-0.067305,-0.031828,0.029361,0.082489,-0.033856,-0.050656,0.026593,-0.016502,0.081590,-0.022007,-0.033161,-0.029363,0.025477,0.020770,-0.007044,0.019011,0.025258,0.032004,-0.062329,-2.466023e-33,0.007679,0.106935,-0.025969,0.053993,0.017424,-0.028920,-0.013960,0.012732,0.050942,0.075999,-0.051276,-0.107104,-0.003849,0.030874,-0.029908,-0.036551,0.063974,0.084598,0.022616,0.005055,-0.101320,0.002418,0.037561,0.024303,-0.057704,-0.017664,0.089402,0.012023,-0.033609,-0.034635,0.046495,-0.089031,0.003557,0.020784,0.053875,0.103901,0.154025,-0.010748,-0.002760,-0.061639,0.042945,0.029622,-0.050750,0.064747,-0.060731,-0.016019,0.011252,-0.005228,-0.053270,-0.110556,0.026254,0.018397,-0.016370,0.094987,-0.003558,0.006035,0.033904,0.057298,-0.005050,0.020855,-0.037758,-0.044358,-0.026687,0.023905,0.055469,-0.028003,-0.033107,-0.028980,-0.001341,0.020634,-0.006998,0.003973,-0.061806,-0.067267,-0.001458,0.011620,-0.018255,0.066499,0.016769,-0.016400,0.061616,-0.053255,-0.048953,0.037567,0.010078,-0.004024,0.083195,0.051541,0.016890,0.088073,0.027472,0.035269,-0.033289,0.055383,-0.039572,-3.635546e-08,-0.002719,0.033059,-0.079617,0.033655,-0.016895,0.006807,0.045821,0.033279,-0.128265,-0.020307,-0.007024,-0.008272,-0.025085,-0.019264,-0.043257,0.065935,-0.040550,-0.015586,-0.059581,-0.071391,0.045279,-0.004918,-0.077854,0.042685,-0.022365,0.043653,-0.069847,-0.001751,0.021806,-0.049379,-0.008623,-0.080029,-0.099434,-0.013117,0.031388,0.044065,0.002988,-0.024362,0.068508,0.017088,-0.093810,-0.054265,0.039885,-0.003044,0.061326,-0.003042,-0.134548,0.010564,-0.089163,-0.028999,-0.014847,-0.049973,0.040078,0.111644,0.038443,-0.061690,0.079270,0.004470,-0.009050,0.059872,0.071281,0.007691,0.010038,0.043835

In [44]:
weekly_df["event_count"] = (
    weekly_df[
        [
            "event_type_Battles",
            "event_type_Explosions/Remote violence",
            "event_type_Protests",
            "event_type_Riots",
            "event_type_Strategic developments",
            "event_type_Violence against civilians"
        ]
    ].sum(axis=1)
)

In [45]:
weekly_df["violent_events"] = (
    weekly_df["event_type_Battles"] +
    weekly_df["event_type_Explosions/Remote violence"] +
    weekly_df["event_type_Violence against civilians"]
)

weekly_df["violent_event_ratio"] = (
    weekly_df["violent_events"] /
    weekly_df["event_count"].replace(0,1)
)

In [46]:
weekly_df["state_actor_ratio"] = (
    weekly_df["actor_State forces"] /
    weekly_df[
        [
            "actor_Civilians",
            "actor_External/Other forces",
            "actor_Identity militia",
            "actor_Political militia",
            "actor_Protesters",
            "actor_Rebel group",
            "actor_Rioters",
            "actor_State forces"
        ]
    ].sum(axis=1).replace(0,1)
)

In [47]:
weekly_df["fatalities_lag2"] = (
    weekly_df.groupby("country")["fatalities"]
    .rolling(2)
    .sum()
    .reset_index(0,drop=True)
)

In [48]:
weekly_df["fatalities_lag4"] = (
    weekly_df.groupby("country")["fatalities"]
    .rolling(4)
    .sum()
    .reset_index(0,drop=True)
)

In [49]:
event_cols = [
    "event_type_Battles",
    "event_type_Explosions/Remote violence",
    "event_type_Protests",
    "event_type_Riots",
    "event_type_Strategic developments",
    "event_type_Violence against civilians"
]

weekly_df["event_diversity"] = (weekly_df[event_cols] > 0).sum(axis=1)

In [50]:
weekly_df["future_fatalities"] = (
    weekly_df.groupby("country")["fatalities"]
    .shift(-1) +
    weekly_df.groupby("country")["fatalities"].shift(-2) +
    weekly_df.groupby("country")["fatalities"].shift(-3) +
    weekly_df.groupby("country")["fatalities"].shift(-4)
)

In [52]:
weekly_df["conflict_escalation"] = (
    weekly_df["future_fatalities"] > 2 * weekly_df["fatalities"]
).astype(int)

In [53]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

X = weekly_df.drop(columns=["conflict_escalation","country","week"])
y = weekly_df["conflict_escalation"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,shuffle=False
)

model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05
)

model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [54]:
probs = model.predict_proba(X_test)[:,1]

In [55]:
risk_index = probs * 100

In [60]:
weekly_df = weekly_df.fillna(0)

In [61]:
weekly_df

,country,week,fatalities,actor_Civilians,actor_External/Other forces,actor_Identity militia,actor_Political militia,actor_Protesters,actor_Rebel group,actor_Rioters,actor_State forces,event_type_Battles,event_type_Explosions/Remote violence,event_type_Protests,event_type_Riots,event_type_Strategic developments,event_type_Violence against civilians,bert_0,bert_1,bert_2,bert_3,bert_4,bert_5,bert_6,bert_7,bert_8,bert_9,bert_10,bert_11,bert_12,bert_13,bert_14,bert_15,bert_16,bert_17,bert_18,bert_19,bert_20,bert_21,bert_22,bert_23,bert_24,bert_25,bert_26,bert_27,bert_28,bert_29,bert_30,bert_31,bert_32,bert_33,bert_34,bert_35,bert_36,bert_37,bert_38,bert_39,bert_40,bert_41,bert_42,bert_43,bert_44,bert_45,bert_46,bert_47,bert_48,bert_49,bert_50,bert_51,bert_52,bert_53,bert_54,bert_55,bert_56,bert_57,bert_58,bert_59,bert_60,bert_61,bert_62,bert_63,bert_64,bert_65,bert_66,bert_67,bert_68,bert_69,bert_70,bert_71,bert_72,bert_73,bert_74,bert_75,bert_76,bert_77,bert_78,bert_79,bert_80,bert_81,bert_82,bert_83,bert_84,bert_85,bert_86,bert_87,bert_88,bert_89,bert_90,bert_91,bert_92,bert_93,bert_94,bert_95,bert_96,bert_97,bert_98,bert_99,bert_100,bert_101,bert_102,bert_103,bert_104,bert_105,bert_106,bert_107,bert_108,bert_109,bert_110,bert_111,bert_112,bert_113,bert_114,bert_115,bert_116,bert_117,bert_118,bert_119,bert_120,bert_121,bert_122,bert_123,bert_124,bert_125,bert_126,bert_127,bert_128,bert_129,bert_130,bert_131,bert_132,bert_133,bert_134,bert_135,bert_136,bert_137,bert_138,bert_139,bert_140,bert_141,bert_142,bert_143,bert_144,bert_145,bert_146,bert_147,bert_148,bert_149,bert_150,bert_151,bert_152,bert_153,bert_154,bert_155,bert_156,bert_157,bert_158,bert_159,bert_160,bert_161,bert_162,bert_163,bert_164,bert_165,bert_166,bert_167,bert_168,bert_169,bert_170,bert_171,bert_172,bert_173,bert_174,bert_175,bert_176,bert_177,bert_178,bert_179,bert_180,bert_181,bert_182,bert_183,bert_184,bert_185,bert_186,bert_187,bert_188,bert_189,bert_190,bert_191,bert_192,bert_193,bert_194,bert_195,bert_196,bert_197,bert_198,bert_199,bert_200,bert_201,bert_202,bert_203,bert_204,bert_205,bert_206,bert_207,bert_208,bert_209,bert_210,bert_211,bert_212,bert_213,bert_214,bert_215,bert_216,bert_217,bert_218,bert_219,bert_220,bert_221,bert_222,bert_223,bert_224,bert_225,bert_226,bert_227,bert_228,bert_229,bert_230,bert_231,bert_232,bert_233,bert_234,bert_235,bert_236,bert_237,bert_238,bert_239,bert_240,bert_241,bert_242,bert_243,bert_244,bert_245,bert_246,bert_247,bert_248,bert_249,bert_250,bert_251,bert_252,bert_253,bert_254,bert_255,bert_256,bert_257,bert_258,bert_259,bert_260,bert_261,bert_262,bert_263,bert_264,bert_265,bert_266,bert_267,bert_268,bert_269,bert_270,bert_271,bert_272,bert_273,bert_274,bert_275,bert_276,bert_277,bert_278,bert_279,bert_280,bert_281,bert_282,bert_283,bert_284,bert_285,bert_286,bert_287,bert_288,bert_289,bert_290,bert_291,bert_292,bert_293,bert_294,bert_295,bert_296,bert_297,bert_298,bert_299,bert_300,bert_301,bert_302,bert_303,bert_304,bert_305,bert_306,bert_307,bert_308,bert_309,bert_310,bert_311,bert_312,bert_313,bert_314,bert_315,bert_316,bert_317,bert_318,bert_319,bert_320,bert_321,bert_322,bert_323,bert_324,bert_325,bert_326,bert_327,bert_328,bert_329,bert_330,bert_331,bert_332,bert_333,bert_334,bert_335,bert_336,bert_337,bert_338,bert_339,bert_340,bert_341,bert_342,bert_343,bert_344,bert_345,bert_346,bert_347,bert_348,bert_349,bert_350,bert_351,bert_352,bert_353,bert_354,bert_355,bert_356,bert_357,bert_358,bert_359,bert_360,bert_361,bert_362,bert_363,bert_364,bert_365,bert_366,bert_367,bert_368,bert_369,bert_370,bert_371,bert_372,bert_373,bert_374,bert_375,bert_376,bert_377,bert_378,bert_379,bert_380,bert_381,bert_382,bert_383,event_count,violent_events,violent_event_ratio,state_actor_ratio,fatalities_lag2,fatalities_lag4,event_diversity,future_fatalities,conflict_escalation
0,Albania,2018-02-05/2018-02-11,0,0.0,0,0,3,0,0,0,0,0,3,0,0,0,0,-0.004577,0.052213,-0.013428,0.011211,0.036307,-0.054521,0.029979,0.015875,-0.013522,0.007654,0.075262,0.034576,0.034227,0.007733,0.014299,0.006027,-0.037861,-0.061685,-0.044873,-0.009208,-0.009583,0.052416,0.010488,0.039543,0.037244,0.031277,0.030355,0.015459,0.009318,-0.012508,0.068945,-0.071190,-0.076967,-0.000708,0.086579,0.013790,0.069294,0.016248,0.059053,0.002398,0.015112,-0.050247,-0.014442,-0.025006,-0.033292,0.036392,0.019320,-0.048067,0.033341,0.008613,-0.021214,0.000114,0.051666,-0.029723,0.011964,-0.123125,-0.002850,-0.008140,0.013732,-0.011845,-0.001733,0.044571,-0.013507,0.010712,0.043654,-0.003774,0.086792,-0.024215,0.076250,-0.022786,0.141448,-0.056762,0.064323,-0.083115,-0.053960,-0.028473,0.033343,-0.013855,-0.035127,0.006836,0.043815,-0.057116,-0.006864,-0.050865,0.013198,0.034177,-0.018652,0.065861,0.034450,0.045977,-0.026328,0.067987,0.050918,0.012911,0.091451,-0.001730,-0.049658,-0.022153,-0.019833,0.059082,-0.018725,0.024923,-0.051831,-0.026581,-0.018802,-0.017455,-0.058505,-0.004476,-0.054460,0.001764,0.014530,-0.008525,0.022865,-0.081648,0.025027,0.032422,0.031260,0.037562,-0.101982,-0.009670,0.037863,-0.001074,-0.106144,0.061678,-0.025968,0.044315,0.009708,-2.011726e-33,-0.011745,0.028096,-0.043258,0.016355,0.051071,-0.004370,-0.064693,0.001086,-0.018974,-0.000970,-0.029089,-0.076010,-0.007495,-0.041127,-0.028890,-0.000385,0.071688,0.056580,-0.034999,-0.076092,-0.030027,0.032400,-0.034451,0.012340,-0.016446,0.122668,0.026531,0.005526,-0.005048,0.006901,-0.025448,0.059884,-0.040282,-0.000602,-0.002051,0.045432,-0.089832,-0.032500,-0.045964,-0.041721,-0.024582,0.010887,-0.035377,0.044585,-0.006946,0.029460,-0.054145,0.025458,0.074783,-0.113167,-0.050288,-0.020872,-0.025954,0.038343,-0.008457,0.039095,-0.014366,-0.015027,0.115356,0.033715,0.091406,0.005663,-0.064024,0.045165,-0.002792,-0.122232,-0.035806,0.027718,0.056298,0.047727,-0.007806,0.023530,0.024159,-0.009314,-0.070454,-0.023251,-0.023625,-0.006407,-0.012235,0.067447,0.021282,-0.021077,0.112738,0.013543,-0.028201,0.038246,-0.012570,0.019347,-0.043342,0.056439,-0.064517,-0.063302,-0.000752,-0.022519,-0.062180,-9.477841e-34,-0.001819,0.029151,-0.089249,-0.013744,-0.022928,0.030638,-0.066004,0.042566,-0.080033,-0.009188,0.014174,-0.008891,0.014300,0.035351,0.035566,0.010426,0.078147,-0.008500,-0.022509,-0.004595,-0.059193,-0.039273,-0.045455,-0.010668,0.005595,0.043986,0.028814,-0.014616,0.007324,0.009233,-0.049708,0.018576,-0.032914,0.070639,0.046408,0.096356,0.079077,0.003085,0.015342,-0.016460,-0.008561,0.112922,-0.001815,0.117971,-0.020666,-0.039605,0.020943,-0.024357,-0.042266,-0.049616,-0.001312,0.026161,-0.042359,-0.016695,0.039572,0.015784,-0.035098,-0.066855,-0.028379,-0.055127,-0.031633,0.027321,-0.078300,0.033905,-0.040010,-0.020627,-0.084120,-0.041035,0.000673,-0.001084,0.047453,0.014741,-0.057267,-0.046467,-0.077508,-0.001683,-0.009706,0.043082,-0.037998,-0.024474,0.073737,-0.038774,-0.068054,0.029669,0.014949,0.002962,0.087735,0.015452,0.047890,-0.051931,-0.059139,0.008289,-0.019443,0.038822,0.040929,-3.466246e-08,-0.015623,0.030250,-0.039610,-0.021166,0.042520,-0.006474,0.050651,0.037452,-0.056772,0.034081,-0.054843,-0.013652,-0.010622,-0.015420,-0.073020,0.048535,-0.034626,-0.007183,-0.016180,-0.031458,0.015842,0.012178,0.004866,-0.004202,-0.009218,0.058340,-0.028885,0.008240,-0.026381,0.025832,-0.014771,-0.015489,-0.064820,-0.060097,-0.055794,0.061962,0.046642,-0.006885,0.012895,-0.080868,-0.069703,-0.043228,0.034805,0.043395,0.013184,-0.000820,-0.038298,-0.063405,-0.009269,0.016603,0.024957,0.012870,0.009336,0.068147,0.019237,-0.047817,-0.013221,-0.030345,0.014207,-0.030345,0.070290,-0.022730,0.006768,0.007278,3,3,1.000000,0.000000,0.0,0.0,1,0.0,0
1,Albania,2018-02-12/2018-02-18,0,0.0,1,0,0,0,0,1,0,0,0,0,1,0,0,0.041451,0.060823,0.027797,0.038895,0.028736,0.116989,0.043393,-0.144543,0.005008,-0.022823,-0.025945,0.020813,0.047004,0.038058,0.007332,-0.007054,0.095035,-0.025240,0.001392,0.038195,-0.056347,-0.061297,-0.054216,0.029580,-0.029655,-0.068390,0.009031,0.013045,0.017465,-0.002805,-0.063461,-0.005919,-0.070654,0.063439,0.060583,0.050999,0.018804,-0.025747,-0.002985,0.000871,0.020348,-0.011700,-0.037369,0.020175,0.021169,-0.000382,-0.080777,-0.005063,-0.020549,0.005990,-0.019516,0.018712,0.037562,-0.072300,-0.000741,-0.078480,0.061870,0.034056,0.066155,0.049109,-0.016393,-0.025216,-0.020070,0.030134,0.036283,0.040564,-0.002451,0.017556,0.093472,-0.009130,0.024671,-0.023546,0.047087,-0.090161,-0.001429,0.004939,-0.076150,-0.034233,0.020590,-0.121122,0.114617,-0.070202,-0.024921,-0.011817,0.016917,0.023862,-0.043784,0.029216,0.037443,0.034070,-0.002062,0.010413,0.011631,0.058735,0.133393,-0.077042,-0.019520,-0.024967,0.014274,0.054980,0.052875,0.042876,0.032358,-0.064551,-0.044932,-0.046790,0.007036,-0.020154,-0.150381,0.041239,0.021658,0.062482,0.045678,0.018744,0.054506,0.085606,-0.020181,-0.023039,0.019189,-0.036327,-0.016894,0.026284,-0.024959,0.029487,-0.080383,-0.010991,-0.049207,-3.074741e-33,-0.009452,-0.030238,-0.010895,-0.032407,0.014785,-0.053062,-0.048056,0.003950,0.060819,-0.038846,0.074095,-0.073922,0.051134,-0.023727,-0.023354,0.035194,0.005876,0.049993,-0.030997,0.015893,0.002115,0.011289,-0.036656,0.083750,-0.108687,0.105934,-0.082867,0.017116,0.025141,0.001015,-0.041089,0.014943,0.083194,0.043857,0.089624,-0.047682,0.029595,-0.026732,-0.020712,-0.047231,-0.029018,0.037618,-0.046695,0.040779,-0.029102,0.054160,-0.022435,-0.042603,0.022358,0.046287,-0.036498,0.147584,-0.042664,-0.024653,0.023112,-0.013923,-0.039030,-0.049137,0.029454,-0.144653,0.066934,0.122300,0.027675,0.045701,0.019015,-0.053799,-0.010790,0.007960,0.063857,-0.045075,-0.067716,0.021940,0.020809,0.000665,-0.022583,-0.025053,0.027059,-0.021558,0.058503,-0.023356,0.021164,0.030915,0.019868,-0.008584,-0.008799,-0.020034,-0.018256,-0.019120,0.009290,0.058927,0.043893,-0.017186,-0.054530,0.052617,-0.015388,4.367132e-34,0.099784,0.013698,-0.030195,-0.027949,-0.016646,-0.101055,-0.073350,0.068985,0.112653,0.040611,0.005349,-0.013974,0.045824,0.027575,-0.019315,-0.135718,0.028132,0.077897,-0.003753,0.023674,-0.006607,-0.027474,-0.013781,-0.083889,-0.032519,0.094881,0.085951,0.025317,-0.088239,-0.009209,0.059284,-0.025226,-0.005227,0.016171,0.025344,-0.017794,0.133870,-0.023943,-0.105041,-0.031904,-0.040052,0.073717,-0.057207,0.135782,-0.053970,0.001268,-0.017856,0.000620,-0.035258,-0.045023,-0.045228,-0.010970,0.060224,-0.160315,-0.002745,-0.027717,-0.009936,-0.023926,0.028300,0.080878,-0.011485,0.014723,-0.108740,-0.141163,0.010661,0.047984,-0.074077,0.095326,0.016158,0.054364,0.062044,-0.005749,0.005071,0.049897,-0.065684,-0.026327,0.062161,0.005239,-0.015408,-0.019706,0.016647,-0.047994,-0.048874,0.009182,0.021023,0.146561,-0.001915,-0.045705,-0.064043,0.011443,0.024232,-0.058137,0.055365,-0.010568,-0.017417,-3.614149e-08,-0.074953,0.012596,0.004302,-0.035575,0.055553,-0.017649,-0.016342,-0.028112,0.030373,0.038392,-0.004935,-0.065183,0.053733,-0.037269,-0.040340,-0.029306,0.009488,-0.060725,-0.087625,-0.042691,-0.052400,-0.019189,0.038741,-0.019295,-0.030219,0.031830,-0.051026,-0.027279,-0.069179,0.111247,-0.092308,0.017067,-0.039225,-0.013072,-0.029676,0.040501,-0.009389,-0.061023,0.036908,-0.125279,-0.007119,0.010780,0.052914,0.024843,0.004467,0.003946,0.061856,0.039128,-0.024055,0.012994,-0.076158,-0.060181,-0.050613,0.043946,0.030683,-0.042630,0.020646,0.084593,-0.006898,0.062060,-0.020137,-0.013739,-0.018947,0.014590,1,0,0.000000,0.000000,0.0,0.0,1,0.0,0
2,Albania,2018-03-19/2018-03-25,0,0.0,0,0,0,0,0,1,1,0,0,0,1,0,0,-0.018453,0.052927,0.011251,0.020172,0.065999,-0.051773,0.062296,0.009563,-0.113556,-0.064120,0.009259,0.002009,0.026507,0.047409,0.028867,0.049510,0.028101,0.005299,-0.013721,-0.051474,-0.000977,-0.013761,0.005384,0.092357,-0.012972,0.029609,-0.011506,0.000973,0.053442,0.018569,0.003195,0.059401,-0.018027,0.023050,0.064879,0.024494,0.016830,-0.051605,0.028352,-0.070816,0.057124,-0.106669,-0.002765,-0.027874,-0.012736,0.026937,0.124872,0.021935,0.009001,-0.072077,0.038181,-0.064962,0.087381,-0.078257,-0.037927,-0.035481,0.035432,-0.014534,0.035582,0.010034,-0.046787,-0.015344,-0.014257,0.028058,0.076939,0.015229,0.044019,-0.022918,0.041068,-0.062267,0.118254,-0.047955,-0.014641,-0.033109,-0.003524,0.025747,-0.026422,0.067735,0.048358,-0.084522,0.000716,-0.070297,0.025193,0.000914,0.058191,-0.025054,-0.078287,0.096116,0.015524,-0.027563,0.013122,0.033097,-0.016512,0.006724,0.029161,-0.039187,0.081412,0.015431,0.016750,0.105479,0.082665,0.088724,-0.098869,-0.015576,-0.001046,-0.014664,-0.041791,-0.031852,-0.053181,0.026235,0.084765,-0.062941,0.039236,-0.026087,-0.028293,0.049044,0.021950,0.074302,-0.026627,0.002631,-0.034115,0.108023,-0.088860,-0.031203,0.043121,0.073293,-0.026330,-3.352946e-33,-0.021172,-0.022597,-0.024244,0.003052,0.004928,0.077536,-0.021534,-0.045822,0.021700,-0.044645,-0.031295,0.016259,0.082646,-0.079494,-0.060343,-0.058516,0.055189,-0.040823,-0.026373,0.034217,0.019618,-0.057268,-0.076948,0.073462,-0.004414,0.078842,0.011944,-0.021533,0.075395,0.010733,-0.025313,-0.004021,0.030802,-0.004209,0.009507,0.053282,-0.011085,-0.040276,-0.032634,-0.080348,-0.058274,0.016862,-0.036719,-0.030278,0.007472,0.042508,-0.034460,0.045357,-0.027230,-0.102143,-0.013642,0.039330,-0.040138,-0.042506,0.031521,0.051383,-0.008946,0.000213,0.037613,0.008493,0.065166,0.053841,-0.089763,0.081435,0.002805,0.043121,-0.006951,0.065625,-0.020265,0.047533,0.039821,0.052767,-0.057471,0.034408,-0.067851,0.038544,-0.030568,-0.056872,-0.058488,0.017126,-0.016934,-0.042631,0.059475,0.010564,0.017006,-0.014920,-0.002574,-0.013561,-0.003545,-0.008297,-0.070841,-0.032960,0.072630,0.069293,-0.041905,1.225291e-33,0.006462,0.078167,-0.033471,-0.032881,-0.021509,-0.012015,0.069357,-0.063783,-0.005132,0.089593,0.014207,-0.073796,-0.021672,0.041658,-0.034478,0.058114,-0.034983,0.133161,0.046450,0.050410,-0.169154,0.041632,-0.046965,0.006916,-0.090031,-0.014449,0.026591,-0.084542,-0.002047,-0.052321,-0.002616,-0.066032,-0.100077,-0.014290,0.013822,0.071968,0.072685,-0.042753,0.044093,0.040663,-0.055346,0.028916,-0.023730,0.121509,-0.106606,0.010908,0.008294,-0.012080,-0.095867,-0.128990,-0.046346,0.040227,-0.032837,-0.019078,-0.043554,-0.068490,-0.045157,0.062852,-0.099851,-0.039309,0.022236,-0.034339,-0.063028,0.035294,-0.005852,-0.028786,-0.059838,0.047496,0.080160,0.032169,0.058041,-0.040513,-0.068345,0.036371,-0.018616,0.045799,-0.004805,0.096160,0.060010,0.012963,0.046443,-0.022991,-0.042562,0.015805,0.040740,-0.011635,0.094015,0.033484,0.023490,-0.028600,0.019161,-0.001635,-0.044569,0.053521,0.058882,-3.471376e-08,0.035877,-0.021867,-0.069353,0.011828,-0.006819,0.000621,0.048845,-0.075696,-0.044046,0.009649,-0.108144,-0.127051,-0.088814,-0.089155,0.031260,0.067246,-0.063803,0.017089,-0.013263,-0.014543,-0.003256,-0.036412,-0.010492,0.045092,-0.100376,-0.004301,0.035076,-0.047879,-0.010855,0.026767,-0.036052,-0.010943,-0.017405,-0.078519,0.053022,0.061384,-0.008857,-0.035908,0.100860,-0.030545,-0.143775,-0.007375,-0.003182,0.008481,0.033077,-0.037335,0.021966,0.010896,-0.013124,-0.054638,0.001646,-0.057087,0.114474,0.068058,0.038387,0.069379,-0.003454,-0.008091,-0.078032,-0.015307,0.084890,0.017045,0.025673,0.005045,1,0,0.000000,0.500000,0.0,0.0,1,0.0,0
3,Albania,2018-03-26/2018-04-01,0,0.0,0,0,0,0,0,1,1,0,0,0,1,0,0,-0.004325,0.112572,0.034390,0.048747,0.001848,-0.011215,0.051443,-0.043494,0.013743,0.050167,0.029741,-0.034164,-0.036019,0.024852,-0.044420,-0.015735,-0.011400,0.037452,-0.116040,-0.058135,-0.030423,-0.014305,0.085072,0.063342,-0.060228,-0.029572,0.027218,0.058163,0.074068,-0.039196,0.000733,-0.041599,-0.161995,0.025801,0.005084,-0.042484,0.007576,-0.006029,0.015606,-0.093400,0.107153,-0.054887,-0.001222,-0.031474,0.100128,0.000936,0.036870,0.018025,0.034814,-0.035714,0.102880,0.002432,0.074001,-0.055518,0.017692,-0.164174,0.003127,0.010980,0.059872,0.029300,0.005603,-0.010869,-0.004602,0.006804,-0.067891,0.003758,0.039071,0.003822,0.061335,0.068696,0.101056,0.006798,0.012352,-0.004573,0.024197,0.002292,-0.037068,0.043765,-0.081284,-0.072697,0.071694,-0.074501,-0.041528,0.037191,0.021516,-0.037580,-0.057895,0.029432,0.073484,0.036809,0.050851,0.117619,0.073755,-0.007731,0.078631,-0.043055,0.027007,0.007261,-0.028300,0.094205,0.063816,0.016874,-0.045311,0.001096,0.006493,-0.015744,-0.070743,-0.120170,-0.078065,0.028470,0.029830,-0.035070,-0.013348,-0.042663,0.009943,-0.038075,0.002882,0.036418,0.038676,0.058872,-0.032859,0.056184,-0.137213,0.053919,0.070694,0.058964,-0.079175,1.263598e-33,-0.018151,-0.042820,-0.019049,-0.006399,0.040395,-0.072112,-0.022857,-0.068136,0.033150,-0.088185,-0.101825,-0.012766,0.020287,-0.111354,0.029816,0.022917,-0.004561,0.001024,-0.064890,0.014494,-0.015441,-0.098172,-0.012492,0.062362,-0.076621,0.034083,-0.005399,-0.033050,0.055076,0.021863,-0.063386,0.007444,0.046309,-0.008531,-0.078606,0.061773,-0.002932,-0.030312,-0.121996,-0.023254,-0.030921,-0.024505,-0.007043,0.008389,0.054433,0.007593,-0.087408,0.019825,-0.003193,-0.033524,-0.039160,-0.012749,0.019856,-0.012076,-0.015576,0.085884,-0.012364,-0.021327,0.037676,0.030731,0.032516,0.007250,-0.044575,0.047720,0.038057,-0.009123,-0.031353,0.081198,-0.008741,-0.002456,-0.001462,0.061237,-0.074113,0.009071,-0.043379,0.009880,-0.067305,-0.031828,0.029361,0.082489,-0.033856,-0.050656,0.026593,-0.016502,0.081590,-0.022007,-0.033161,-0.029363,0.025477,0.020770,-0.007044,0.019011,0.025258,0.032004,-0.062329,-2.466023e-33,0.007679,0.106935,-0.025969,0.053993,0.017424,-0.028920,-0.013960,0.012732,0.050942,0.075999,-0.051276,-0.107104,-0.003849,0.030874,-0.029908,-0.036551,0.063974,0.084598,0.022616,0.005055,-0.101320,0.002418,0.037561,0.024303,-0.057704,-0.017664,0.089402,0.012023,-0.033609,-0.034635,0.046495,-0.089031,0.003557,0.020784,0.053875,0.103901,0.154025,-0.010748,-0.002760,-0.061639,0.042945,0.029622,-0.050750,0.064747,-0.060731,-0.016019,0.011252,-0.005228,-0.053270,-0.110556,0.026254,0.018397,-0.016370,0.094987,-0.003558,0.006035,0.033904,0.057298,-0.005050,0.020855,-0.037758,-0.044358,-0.026687,0.023905,0.055469,-0.028003,-0.033107,-0.028980,-0.001341,0.020634,-0.006998,0.003973,-0.061806,-0.067267,-0.001458,0.011620,-0.018255,0.066499,0.016769,-0.016400,0.061616,-0.053255,-0.048953,0.037567,0.010078,-0.004024,0.083195,0.051541,0.016890,0.088073,0.027472,0.035269,-0.033289,0.055383,-0.039572,-3.635546e-08,-0.002719,0.033059,-0.079617,0.033655,-0.016895,0.006807,0.045821,0.033279,-0.128265,-0.020307,-0.007024,-0.008272,-0.025085,-0.019264,-0.043257,0.065935,-0.040550,-0.015586,-0.059581,-0.071391,0.045279,-0.004918,-0.077854,0.042685,-0.022365,0.043653,-0.069847,-0.001751,0.021806,-0.049379,-0.008623,-0.080029,-0.099434,-0.013117,0.031388,0.044065,0.002988,-0.024362,0.068508,0.017088,-0.093810,-0.054265,0.039885,-0.003044,0.061326,-0.003042,-0.134548,0.010564,-0.089163,-0.028999,-0.014847,-0.049973,0.040078,0.111644,0.038443,-0.061690,0.079270,0.004470,-0.009050,0.059872,0.071281,0.007691,0.010038,0.043835,1,0,0.000000,0.500000,0.0,0.0,1,0.0,0

In [62]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1299
           1       0.99      1.00      0.99      3345

    accuracy                           0.99      4644
   macro avg       0.99      0.99      0.99      4644
weighted avg       0.99      0.99      0.99      4644